// File generated from our OpenAPI spec and handwritten Terraform acceptance templates.
// Terraform acceptance coverage registry emitted by sdk-codegen from handwritten sources.

package runner

type CoverageEntry struct {
	Surface   string
	Kind      string
	Group     string
	Status    string
	CaseNames []string
	Reason    string
}

var CoverageRegistry = []CoverageEntry{
	{
		Surface:   "stripe_person",
		Kind:      "resource",
		Group:     "connect",
		Status:    "limited",
		CaseNames: []string{"person_basic", "person_relationship_owner"},
		Reason:    "",
	},
	{
		Surface:   "stripe_apple_pay_domain",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"apple_pay_domain_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_fee_refund",
		Kind:      "action",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"fee_refund_action_regression"},
		Reason:    "",
	},
	{
		Surface:   "stripe_billing_alert",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"billing_alert_basic", "billing_alert_recurring_threshold"},
		Reason:    "",
	},
	{
		Surface:   "stripe_billing_credit_grant",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"billing_credit_grant_basic", "billing_credit_grant_amount_priority_update"},
		Reason:    "",
	},
	{
		Surface:   "stripe_billing_meter",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"billing_meter_basic", "billing_meter_count_aggregation", "billing_meter_deactivate", "billing_meter_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_billing_portal_configuration",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"billing_portal_configuration_basic", "billing_portal_configuration_login_cancel"},
		Reason:    "",
	},
	{
		Surface:   "stripe_charge",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"charge_basic", "charge_customer_shipping"},
		Reason:    "",
	},
	{
		Surface:   "stripe_checkout_session",
		Kind:      "ephemeral",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"checkout_session_ephemeral"},
		Reason:    "",
	},
	{
		Surface:   "stripe_climate_order",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"climate_order_basic", "climate_order_explicit_currency"},
		Reason:    "",
	},
	{
		Surface:   "stripe_coupon",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"coupon_percent_off", "coupon_amount_off", "coupon_repeating", "coupon_applies_to", "coupon_applies_to_product_update", "coupon_applies_to_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_credit_note",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"credit_note_basic", "credit_note_effective_at_custom_line"},
		Reason:    "",
	},
	{
		Surface:   "stripe_customer",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"customer_basic", "customer_profile", "customer_invoice_tax", "customer_legacy_upgrade", "customer_invoice_tax_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_customer_balance_transaction",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"customer_balance_transaction_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_delegated_checkout_requested_session",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_entitlements_feature",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"entitlements_feature_basic", "entitlements_feature_metadata_update", "entitlements_feature_rename", "entitlements_feature_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_file",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"file_upload_basic", "file_upload_file_link_data"},
		Reason:    "",
	},
	{
		Surface:   "stripe_file_link",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"file_link_basic", "file_link_no_expiry"},
		Reason:    "",
	},
	{
		Surface:   "stripe_financial_connections_session",
		Kind:      "ephemeral",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"financial_connections_session_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_forwarding_request",
		Kind:      "action",
		Group:     "forwarding",
		Status:    "limited",
		CaseNames: []string{"forwarding_request_basic", "forwarding_request_metadata", "forwarding_request_action_regression"},
		Reason:    "",
	},
	{
		Surface:   "stripe_fx_quote",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_fr_meal_vouchers_onboarding",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_identity_blocklist_entry",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_identity_verification_session",
		Kind:      "ephemeral",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"identity_verification_session_basic", "identity_verification_session_provided_details", "identity_verification_session_document_options"},
		Reason:    "",
	},
	{
		Surface:   "stripe_invoice",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"invoice_basic", "invoice_send_invoice_fields"},
		Reason:    "",
	},
	{
		Surface:   "stripe_invoice_item",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"invoice_item_basic", "invoice_item_attached_invoice", "invoice_item_pricing_price_regression", "invoice_item_period_quantity"},
		Reason:    "",
	},
	{
		Surface:   "stripe_issuing_card",
		Kind:      "resource",
		Group:     "issuing",
		Status:    "limited",
		CaseNames: []string{"issuing_card_basic", "issuing_card_lifecycle_controls"},
		Reason:    "",
	},
	{
		Surface:   "stripe_issuing_cardholder",
		Kind:      "resource",
		Group:     "issuing",
		Status:    "limited",
		CaseNames: []string{"issuing_cardholder_basic", "issuing_cardholder_preferences_controls"},
		Reason:    "",
	},
	{
		Surface:   "stripe_issuing_dispute",
		Kind:      "resource",
		Group:     "issuing",
		Status:    "limited",
		CaseNames: []string{"issuing_dispute_basic", "issuing_dispute_other"},
		Reason:    "",
	},
	{
		Surface:   "stripe_issuing_personalization_design",
		Kind:      "resource",
		Group:     "issuing",
		Status:    "limited",
		CaseNames: []string{"issuing_personalization_design_basic", "issuing_personalization_design_default_toggle"},
		Reason:    "",
	},
	{
		Surface:   "stripe_issuing_program",
		Kind:      "resource",
		Group:     "issuing",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_margin",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_order",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_payment_intent",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"payment_intent_basic", "payment_intent_shipping", "payment_intent_setup_future_usage"},
		Reason:    "",
	},
	{
		Surface:   "stripe_payment_location",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_payment_link",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"payment_link_basic", "payment_link_checkout_controls"},
		Reason:    "",
	},
	{
		Surface:   "stripe_payment_method",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"payment_method_basic", "payment_method_allow_redisplay"},
		Reason:    "",
	},
	{
		Surface:   "stripe_payment_method_configuration",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"payment_method_configuration_basic", "payment_method_configuration_wallet_preferences"},
		Reason:    "",
	},
	{
		Surface:   "stripe_payment_method_domain",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"payment_method_domain_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_payout",
		Kind:      "action",
		Group:     "connect",
		Status:    "limited",
		CaseNames: []string{"payout_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_plan",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"plan_basic", "plan_interval_trial"},
		Reason:    "",
	},
	{
		Surface:   "stripe_price",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"price_basic", "price_active_toggle", "price_decimal_amounts", "price_decimal_amounts_legacy_upgrade", "price_decimal_amounts_subcent_precision", "price_decimal_tiers", "price_lookup_key", "price_transform_quantity", "price_tiered", "price_tiered_legacy_upgrade", "price_one_time"},
		Reason:    "",
	},
	{
		Surface:   "stripe_product",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"product_basic", "product_active_toggle", "product_images_url", "product_marketing_features", "product_shippable", "product_statement_descriptor", "product_default_price_data", "product_default_price_data_legacy_upgrade", "product_default_price_data_decimal_amounts"},
		Reason:    "",
	},
	{
		Surface:   "stripe_product_feature",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"product_feature_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_promotion_code",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"promotion_code_basic", "promotion_code_customer", "promotion_code_restrictions", "promotion_code_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_privacy_redaction_job",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_quote",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"quote_basic", "quote_send_invoice_fields"},
		Reason:    "",
	},
	{
		Surface:   "stripe_radar_account_evaluation",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_radar_value_list",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"radar_value_list_basic", "radar_value_list_email_alias_update"},
		Reason:    "",
	},
	{
		Surface:   "stripe_radar_value_list_item",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"radar_value_list_item_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_refund",
		Kind:      "action",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"refund_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_reporting_report_run",
		Kind:      "ephemeral",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"reporting_report_run_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_setup_intent",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"setup_intent_basic", "setup_intent_automatic_payment_methods"},
		Reason:    "",
	},
	{
		Surface:   "stripe_shipping_rate",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"shipping_rate_basic", "shipping_rate_tax_behavior", "shipping_rate_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_shared_payment_issued_token",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_source",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"source_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_subscription",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"subscription_basic", "subscription_trial_settings"},
		Reason:    "",
	},
	{
		Surface:   "stripe_subscription_item",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"subscription_item_basic", "subscription_item_tax_rates"},
		Reason:    "",
	},
	{
		Surface:   "stripe_subscription_schedule",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"subscription_schedule_basic", "subscription_schedule_default_settings", "subscription_schedule_phase_quantity", "subscription_schedule_start_date_regression"},
		Reason:    "",
	},
	{
		Surface:   "stripe_tax_calculation",
		Kind:      "ephemeral",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"tax_calculation_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_tax_registration",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"tax_registration_basic", "tax_registration_canada_simplified"},
		Reason:    "",
	},
	{
		Surface:   "stripe_tax_id",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"tax_id_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_tax_location",
		Kind:      "resource",
		Group:     "base",
		Status:    "skipped",
		CaseNames: nil,
		Reason:    "Preview-only Terraform resource without a handwritten acceptance case in this suite.",
	},
	{
		Surface:   "stripe_tax_rate",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"tax_rate_basic", "tax_rate_tax_type", "tax_rate_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_terminal_configuration",
		Kind:      "resource",
		Group:     "terminal",
		Status:    "limited",
		CaseNames: []string{"terminal_configuration_basic", "terminal_configuration_tipping"},
		Reason:    "",
	},
	{
		Surface:   "stripe_terminal_location",
		Kind:      "resource",
		Group:     "terminal",
		Status:    "limited",
		CaseNames: []string{"terminal_location_basic", "terminal_location_configuration_override"},
		Reason:    "",
	},
	{
		Surface:   "stripe_terminal_reader",
		Kind:      "resource",
		Group:     "terminal",
		Status:    "limited",
		CaseNames: []string{"terminal_reader_basic", "terminal_reader_label_update", "terminal_reader_metadata_update", "terminal_reader_registration_code_regression"},
		Reason:    "",
	},
	{
		Surface:   "stripe_token",
		Kind:      "ephemeral",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"token_card_ephemeral", "token_bank_account_ephemeral", "token_pii_ephemeral"},
		Reason:    "",
	},
	{
		Surface:   "stripe_topup",
		Kind:      "action",
		Group:     "connect",
		Status:    "limited",
		CaseNames: []string{"topup_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_transfer",
		Kind:      "action",
		Group:     "connect",
		Status:    "limited",
		CaseNames: []string{"transfer_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_transfer_reversal",
		Kind:      "action",
		Group:     "connect",
		Status:    "limited",
		CaseNames: []string{"transfer_reversal_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_treasury_credit_reversal",
		Kind:      "action",
		Group:     "treasury",
		Status:    "limited",
		CaseNames: []string{"treasury_credit_reversal_action"},
		Reason:    "",
	},
	{
		Surface:   "stripe_treasury_debit_reversal",
		Kind:      "action",
		Group:     "treasury",
		Status:    "limited",
		CaseNames: []string{"treasury_debit_reversal_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_treasury_financial_account",
		Kind:      "resource",
		Group:     "treasury",
		Status:    "limited",
		CaseNames: []string{"treasury_financial_account_basic", "treasury_financial_account_money_movement_features"},
		Reason:    "",
	},
	{
		Surface:   "stripe_treasury_inbound_transfer",
		Kind:      "action",
		Group:     "treasury",
		Status:    "limited",
		CaseNames: []string{"treasury_inbound_transfer_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_treasury_outbound_payment",
		Kind:      "action",
		Group:     "treasury",
		Status:    "limited",
		CaseNames: []string{"treasury_outbound_payment_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_treasury_outbound_transfer",
		Kind:      "action",
		Group:     "treasury",
		Status:    "limited",
		CaseNames: []string{"treasury_outbound_transfer_basic"},
		Reason:    "",
	},
	{
		Surface:   "stripe_v2_core_event_destination",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"v2_core_event_destination_basic", "v2_core_event_destination_snapshot", "v2_core_event_destination_legacy_upgrade"},
		Reason:    "",
	},
	{
		Surface:   "stripe_webhook_endpoint",
		Kind:      "resource",
		Group:     "base",
		Status:    "limited",
		CaseNames: []string{"webhook_endpoint_connect", "webhook_endpoint_api_version", "webhook_endpoint_url_update", "webhook_endpoint_url_legacy_upgrade"},
		Reason:    "",
	},
}
