// File generated from our OpenAPI spec and handwritten Terraform acceptance templates.
// Handwritten Terraform acceptance source emitted by sdk-codegen.
package cases

import "testing"

func TestAccManagedPersonBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"connect",
		nil,
		"person_basic",
		"stripe_person",
		"stripe_person.test",
		"person_basic_create.tf",
		"person_basic_update.tf",
		false,
		verifyPerson(personExpectations{
			Address:                "stripe_person.test",
			ExpectedFirstName:      "Ada",
			ExpectedLastName:       "Lovelace",
			ExpectedEmail:          "sdk-codegen+person-create@example.com",
			ExpectedPhone:          "+15555550131",
			ExpectedAddressLine1:   "100 Market St",
			ExpectedAddressLine2:   "",
			ExpectedCity:           "San Francisco",
			ExpectedState:          "CA",
			ExpectedPostalCode:     "94105",
			ExpectedCountry:        "US",
			ExpectedTitle:          "Chief Architect",
			ExpectedRepresentative: false,
			ExpectedExecutive:      true,
			ExpectedDirector:       true,
			ExpectedDOBDay:         10,
			ExpectedDOBMonth:       12,
			ExpectedDOBYear:        1990,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "person_basic",
				"phase": "create",
			},
		}),
		verifyPerson(personExpectations{
			Address:                "stripe_person.test",
			ExpectedFirstName:      "Ada",
			ExpectedLastName:       "Lovelace",
			ExpectedEmail:          "sdk-codegen+person-update@example.com",
			ExpectedPhone:          "+15555550132",
			ExpectedAddressLine1:   "100 Market St",
			ExpectedAddressLine2:   "",
			ExpectedCity:           "San Francisco",
			ExpectedState:          "CA",
			ExpectedPostalCode:     "94105",
			ExpectedCountry:        "US",
			ExpectedTitle:          "Chief Scientist",
			ExpectedRepresentative: false,
			ExpectedExecutive:      true,
			ExpectedDirector:       true,
			ExpectedDOBDay:         10,
			ExpectedDOBMonth:       12,
			ExpectedDOBYear:        1990,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "person_basic",
				"phase": "update",
			},
		}),
		verifyPersonDestroyMissing,
	)
}

func TestAccManagedPersonRelationshipOwner(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"connect",
		nil,
		"person_relationship_owner",
		"stripe_person",
		"stripe_person.test",
		"person_relationship_owner_create.tf",
		"person_relationship_owner_update.tf",
		false,
		verifyPerson(personExpectations{
			Address:                   "stripe_person.test",
			ExpectedFirstName:         "Katherine",
			ExpectedLastName:          "Johnson",
			ExpectedEmail:             "sdk-codegen+person-owner-create@example.com",
			ExpectedPhone:             "+15555550133",
			ExpectedAddressLine1:      "500 Howard St",
			ExpectedAddressLine2:      "Suite 700",
			ExpectedCity:              "San Francisco",
			ExpectedState:             "CA",
			ExpectedPostalCode:        "94105",
			ExpectedCountry:           "US",
			ExpectedNationality:       "US",
			ExpectedPoliticalExposure: "none",
			ExpectedTitle:             "Managing Member",
			ExpectedRepresentative:    false,
			ExpectedExecutive:         false,
			ExpectedDirector:          false,
			CheckOwner:                true,
			ExpectedOwner:             true,
			CheckPercentOwnership:     true,
			ExpectedPercentOwnership:  25,
			ExpectedDOBDay:            26,
			ExpectedDOBMonth:          8,
			ExpectedDOBYear:           1918,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "person_relationship_owner",
				"phase": "create",
			},
		}),
		verifyPerson(personExpectations{
			Address:                   "stripe_person.test",
			ExpectedFirstName:         "Katherine",
			ExpectedLastName:          "Johnson",
			ExpectedEmail:             "sdk-codegen+person-owner-update@example.com",
			ExpectedPhone:             "+15555550134",
			ExpectedAddressLine1:      "550 Howard St",
			ExpectedAddressLine2:      "Floor 8",
			ExpectedCity:              "San Francisco",
			ExpectedState:             "CA",
			ExpectedPostalCode:        "94105",
			ExpectedCountry:           "US",
			ExpectedNationality:       "US",
			ExpectedPoliticalExposure: "none",
			ExpectedTitle:             "Principal Owner",
			ExpectedRepresentative:    false,
			ExpectedExecutive:         false,
			ExpectedDirector:          true,
			CheckOwner:                true,
			ExpectedOwner:             true,
			CheckPercentOwnership:     true,
			ExpectedPercentOwnership:  35,
			ExpectedDOBDay:            26,
			ExpectedDOBMonth:          8,
			ExpectedDOBYear:           1918,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "person_relationship_owner",
				"phase": "update",
			},
		}),
		verifyPersonDestroyMissing,
	)
}

func TestAccManagedTerminalLocationBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"terminal",
		nil,
		"terminal_location_basic",
		"stripe_terminal_location",
		"stripe_terminal_location.test",
		"terminal_location_basic_create.tf",
		"terminal_location_basic_update.tf",
		true,
		verifyTerminalLocation(terminalLocationExpectations{
			Address:              "stripe_terminal_location.test",
			ExpectedDisplayName:  "SDK Codegen Terminal Location Create",
			ExpectedPhone:        "+15555550141",
			ExpectedAddressLine1: "100 Market St",
			ExpectedCity:         "San Francisco",
			ExpectedState:        "CA",
			ExpectedPostalCode:   "94105",
			ExpectedCountry:      "US",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "terminal_location_basic",
				"phase": "create",
			},
		}),
		verifyTerminalLocation(terminalLocationExpectations{
			Address:              "stripe_terminal_location.test",
			ExpectedDisplayName:  "SDK Codegen Terminal Location Update",
			ExpectedPhone:        "+15555550142",
			ExpectedAddressLine1: "200 Mission St",
			ExpectedCity:         "San Francisco",
			ExpectedState:        "CA",
			ExpectedPostalCode:   "94105",
			ExpectedCountry:      "US",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "terminal_location_basic",
				"phase": "update",
			},
		}),
		verifyTerminalLocationDestroyMissing,
	)
}

func TestAccManagedTerminalLocationConfigurationOverride(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"terminal",
		nil,
		"terminal_location_configuration_override",
		"stripe_terminal_location",
		"stripe_terminal_location.test",
		"terminal_location_configuration_override_create.tf",
		"terminal_location_configuration_override_update.tf",
		true,
		verifyTerminalLocation(terminalLocationExpectations{
			Address:                              "stripe_terminal_location.test",
			ExpectedDisplayName:                  "SDK Codegen Terminal Override Create",
			ExpectedPhone:                        "+15555550143",
			ExpectedAddressLine1:                 "300 Howard St",
			ExpectedAddressLine2:                 "Suite 400",
			ExpectedCity:                         "San Francisco",
			ExpectedState:                        "CA",
			ExpectedPostalCode:                   "94105",
			ExpectedCountry:                      "US",
			ExpectedConfigurationOverrideAddress: "stripe_terminal_configuration.override",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "terminal_location_configuration_override",
				"phase": "create",
			},
		}),
		verifyTerminalLocation(terminalLocationExpectations{
			Address:                              "stripe_terminal_location.test",
			ExpectedDisplayName:                  "SDK Codegen Terminal Override Update",
			ExpectedPhone:                        "+15555550144",
			ExpectedAddressLine1:                 "400 Spear St",
			ExpectedAddressLine2:                 "Floor 9",
			ExpectedCity:                         "San Francisco",
			ExpectedState:                        "CA",
			ExpectedPostalCode:                   "94105",
			ExpectedCountry:                      "US",
			ExpectedConfigurationOverrideAddress: "stripe_terminal_configuration.override",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "terminal_location_configuration_override",
				"phase": "update",
			},
		}),
		verifyTerminalLocationDestroyMissing,
	)
}

func TestAccManagedTerminalConfigurationBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"terminal",
		nil,
		"terminal_configuration_basic",
		"stripe_terminal_configuration",
		"stripe_terminal_configuration.test",
		"terminal_configuration_basic_create.tf",
		"terminal_configuration_basic_update.tf",
		true,
		verifyTerminalConfiguration(terminalConfigurationExpectations{
			Address:                       "stripe_terminal_configuration.test",
			ExpectedName:                  "SDK Codegen Terminal Configuration Create",
			ExpectedOfflineEnabled:        true,
			ExpectedCellularEnabled:       false,
			ExpectedRebootWindowStartHour: 1,
			ExpectedRebootWindowEndHour:   2,
		}),
		verifyTerminalConfiguration(terminalConfigurationExpectations{
			Address:                       "stripe_terminal_configuration.test",
			ExpectedName:                  "SDK Codegen Terminal Configuration Update",
			ExpectedOfflineEnabled:        false,
			ExpectedCellularEnabled:       true,
			ExpectedRebootWindowStartHour: 3,
			ExpectedRebootWindowEndHour:   4,
		}),
		verifyTerminalConfigurationDestroyMissing,
	)
}

func TestAccManagedTerminalConfigurationTipping(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"terminal",
		nil,
		"terminal_configuration_tipping",
		"stripe_terminal_configuration",
		"stripe_terminal_configuration.test",
		"terminal_configuration_tipping_create.tf",
		"terminal_configuration_tipping_update.tf",
		true,
		verifyTerminalConfiguration(terminalConfigurationExpectations{
			Address:                          "stripe_terminal_configuration.test",
			ExpectedName:                     "SDK Codegen Terminal Tips Create",
			ExpectedOfflineEnabled:           true,
			ExpectedCellularEnabled:          true,
			ExpectedRebootWindowStartHour:    5,
			ExpectedRebootWindowEndHour:      6,
			ExpectedTippingUSDFixedAmounts:   []int64{100, 200, 300},
			ExpectedTippingUSDPercentages:    []int64{15, 20, 25},
			ExpectedTippingUSDSmartThreshold: 2000,
		}),
		verifyTerminalConfiguration(terminalConfigurationExpectations{
			Address:                          "stripe_terminal_configuration.test",
			ExpectedName:                     "SDK Codegen Terminal Tips Update",
			ExpectedOfflineEnabled:           false,
			ExpectedCellularEnabled:          true,
			ExpectedRebootWindowStartHour:    7,
			ExpectedRebootWindowEndHour:      8,
			ExpectedTippingUSDFixedAmounts:   []int64{150, 250, 350},
			ExpectedTippingUSDPercentages:    []int64{18, 22, 28},
			ExpectedTippingUSDSmartThreshold: 3000,
		}),
		verifyTerminalConfigurationDestroyMissing,
	)
}

func TestAccManagedIssuingCardholderBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		[]string{"STRIPE_ISSUING_FINANCIAL_ACCOUNT"},
		"issuing_cardholder_basic",
		"stripe_issuing_cardholder",
		"stripe_issuing_cardholder.test",
		"issuing_cardholder_basic_create.tf",
		"issuing_cardholder_basic_update.tf",
		true,
		verifyIssuingCardholder(issuingCardholderExpectations{
			Address:                   "stripe_issuing_cardholder.test",
			ExpectedName:              "SDK Cardholder Create",
			ExpectedEmail:             "sdk-codegen+cardholder-create@example.com",
			ExpectedPhoneNumber:       "+15555550151",
			ExpectedType:              "individual",
			ExpectedStatus:            "active",
			ExpectedFirstName:         "Grace",
			ExpectedLastName:          "Hopper",
			ExpectedBillingLine1:      "100 Main St",
			ExpectedBillingCity:       "San Francisco",
			ExpectedBillingPostalCode: "94105",
			ExpectedBillingCountry:    "US",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_cardholder_basic",
				"phase": "create",
			},
		}),
		verifyIssuingCardholder(issuingCardholderExpectations{
			Address:                   "stripe_issuing_cardholder.test",
			ExpectedName:              "SDK Cardholder Create",
			ExpectedEmail:             "sdk-codegen+cardholder-update@example.com",
			ExpectedPhoneNumber:       "+15555550152",
			ExpectedType:              "individual",
			ExpectedStatus:            "inactive",
			ExpectedFirstName:         "Grace",
			ExpectedLastName:          "Hopper",
			ExpectedBillingLine1:      "100 Main St",
			ExpectedBillingCity:       "San Francisco",
			ExpectedBillingPostalCode: "94105",
			ExpectedBillingCountry:    "US",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_cardholder_basic",
				"phase": "update",
			},
		}),
		verifyIssuingCardholderDestroyStillExists,
	)
}

func TestAccManagedIssuingCardholderPreferencesControls(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		nil,
		"issuing_cardholder_preferences_controls",
		"stripe_issuing_cardholder",
		"stripe_issuing_cardholder.test",
		"issuing_cardholder_preferences_controls_create.tf",
		"issuing_cardholder_preferences_controls_update.tf",
		true,
		verifyIssuingCardholder(issuingCardholderExpectations{
			Address:                        "stripe_issuing_cardholder.test",
			ExpectedName:                   "SDK Pref Cardholder",
			ExpectedEmail:                  "sdk-codegen+cardholder-preferences-create@example.com",
			ExpectedPhoneNumber:            "+15555550153",
			ExpectedType:                   "individual",
			ExpectedStatus:                 "active",
			ExpectedFirstName:              "Grace",
			ExpectedLastName:               "Hopper",
			ExpectedBillingLine1:           "500 Howard St",
			ExpectedBillingCity:            "San Francisco",
			ExpectedBillingPostalCode:      "94105",
			ExpectedBillingCountry:         "US",
			ExpectedPreferredLocales:       []string{"en", "fr"},
			ExpectedAllowedCardPresences:   []string{"present"},
			ExpectedSpendingLimitAmount:    5000,
			ExpectedSpendingLimitInterval:  "weekly",
			ExpectedSpendingLimitsCurrency: "usd",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_cardholder_preferences_controls",
				"phase": "create",
			},
		}),
		verifyIssuingCardholder(issuingCardholderExpectations{
			Address:                        "stripe_issuing_cardholder.test",
			ExpectedName:                   "SDK Pref Cardholder",
			ExpectedEmail:                  "sdk-codegen+cardholder-preferences-update@example.com",
			ExpectedPhoneNumber:            "+15555550154",
			ExpectedType:                   "individual",
			ExpectedStatus:                 "inactive",
			ExpectedFirstName:              "Grace",
			ExpectedLastName:               "Hopper",
			ExpectedBillingLine1:           "500 Howard St",
			ExpectedBillingCity:            "San Francisco",
			ExpectedBillingPostalCode:      "94105",
			ExpectedBillingCountry:         "US",
			ExpectedPreferredLocales:       []string{"en", "es"},
			ExpectedAllowedCardPresences:   []string{"not_present"},
			ExpectedSpendingLimitAmount:    7000,
			ExpectedSpendingLimitInterval:  "monthly",
			ExpectedSpendingLimitsCurrency: "usd",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_cardholder_preferences_controls",
				"phase": "update",
			},
		}),
		verifyIssuingCardholderDestroyStillExists,
	)
}

func TestAccManagedIssuingCardBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		nil,
		"issuing_card_basic",
		"stripe_issuing_card",
		"stripe_issuing_card.test",
		"issuing_card_basic_create.tf",
		"issuing_card_basic_update.tf",
		true,
		verifyIssuingCard(issuingCardExpectations{
			Address:                       "stripe_issuing_card.test",
			ExpectedCardholderAddress:     "stripe_issuing_cardholder.cardholder",
			ExpectedCurrency:              "usd",
			ExpectedType:                  "virtual",
			ExpectedStatus:                "inactive",
			ExpectedLifecyclePaymentCount: 0,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_card_basic",
				"phase": "create",
			},
		}),
		verifyIssuingCard(issuingCardExpectations{
			Address:                       "stripe_issuing_card.test",
			ExpectedCardholderAddress:     "stripe_issuing_cardholder.cardholder",
			ExpectedCurrency:              "usd",
			ExpectedType:                  "virtual",
			ExpectedStatus:                "inactive",
			ExpectedLifecyclePaymentCount: 0,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_card_basic",
				"phase": "update",
			},
		}),
		verifyIssuingCardDestroyStillExists,
	)
}

func TestAccManagedIssuingCardLifecycleControls(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		nil,
		"issuing_card_lifecycle_controls",
		"stripe_issuing_card",
		"stripe_issuing_card.test",
		"issuing_card_lifecycle_controls_create.tf",
		"issuing_card_lifecycle_controls_update.tf",
		true,
		verifyIssuingCard(issuingCardExpectations{
			Address:                       "stripe_issuing_card.test",
			ExpectedCardholderAddress:     "stripe_issuing_cardholder.cardholder",
			ExpectedCurrency:              "usd",
			ExpectedType:                  "virtual",
			ExpectedStatus:                "inactive",
			ExpectedLifecyclePaymentCount: 2,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_card_lifecycle_controls",
				"phase": "create",
			},
		}),
		verifyIssuingCard(issuingCardExpectations{
			Address:                       "stripe_issuing_card.test",
			ExpectedCardholderAddress:     "stripe_issuing_cardholder.cardholder",
			ExpectedCurrency:              "usd",
			ExpectedType:                  "virtual",
			ExpectedStatus:                "inactive",
			ExpectedLifecyclePaymentCount: 4,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_card_lifecycle_controls",
				"phase": "update",
			},
		}),
		verifyIssuingCardDestroyStillExists,
	)
}

func TestAccManagedIssuingDisputeBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		[]string{"STRIPE_ISSUING_DISPUTE_TRANSACTION"},
		"issuing_dispute_basic",
		"stripe_issuing_dispute",
		"stripe_issuing_dispute.test",
		"issuing_dispute_basic_create.tf",
		"issuing_dispute_basic_update.tf",
		true,
		verifyIssuingDispute(issuingDisputeExpectations{
			Address:                       "stripe_issuing_dispute.test",
			ExpectedStatus:                "unsubmitted",
			ExpectedReason:                "fraudulent",
			ExpectedFraudulentExplanation: "sdk-codegen issuing dispute create",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_dispute_basic",
				"phase": "create",
			},
		}),
		verifyIssuingDispute(issuingDisputeExpectations{
			Address:                       "stripe_issuing_dispute.test",
			ExpectedStatus:                "unsubmitted",
			ExpectedReason:                "fraudulent",
			ExpectedFraudulentExplanation: "sdk-codegen issuing dispute update",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_dispute_basic",
				"phase": "update",
			},
		}),
		verifyIssuingDisputeDestroyStillExists,
	)
}

func TestAccManagedIssuingDisputeOther(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		[]string{"STRIPE_ISSUING_DISPUTE_OTHER_TRANSACTION"},
		"issuing_dispute_other",
		"stripe_issuing_dispute",
		"stripe_issuing_dispute.test",
		"issuing_dispute_other_create.tf",
		"issuing_dispute_other_update.tf",
		true,
		verifyIssuingDispute(issuingDisputeExpectations{
			Address:                    "stripe_issuing_dispute.test",
			ExpectedStatus:             "unsubmitted",
			ExpectedReason:             "other",
			ExpectedOtherExplanation:   "sdk-codegen issuing dispute other create",
			ExpectedProductDescription: "SDK Codegen other dispute create",
			ExpectedProductType:        "service",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_dispute_other",
				"phase": "create",
			},
		}),
		verifyIssuingDispute(issuingDisputeExpectations{
			Address:                    "stripe_issuing_dispute.test",
			ExpectedStatus:             "unsubmitted",
			ExpectedReason:             "other",
			ExpectedOtherExplanation:   "sdk-codegen issuing dispute other update",
			ExpectedProductDescription: "SDK Codegen other dispute update",
			ExpectedProductType:        "merchandise",
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_dispute_other",
				"phase": "update",
			},
		}),
		verifyIssuingDisputeDestroyStillExists,
	)
}

func TestAccManagedIssuingPersonalizationDesignBasic(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		[]string{"STRIPE_ISSUING_PHYSICAL_BUNDLE", "STRIPE_ISSUING_CARD_LOGO"},
		"issuing_personalization_design_basic",
		"stripe_issuing_personalization_design",
		"stripe_issuing_personalization_design.test",
		"issuing_personalization_design_basic_create.tf",
		"",
		true,
		verifyIssuingPersonalizationDesign(issuingPersonalizationDesignExpectations{
			Address:               "stripe_issuing_personalization_design.test",
			ExpectedName:          "SDK Codegen Personalization Create",
			CompareStateLookupKey: true,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_personalization_design_basic",
				"phase": "create",
			},
		}),
		nil,
		verifyIssuingPersonalizationDesignDestroyStillExists,
	)
}

func TestAccManagedIssuingPersonalizationDesignDefaultToggle(t *testing.T) {
	runManagedCaseForGroup(
		t,
		"issuing",
		[]string{"STRIPE_ISSUING_PHYSICAL_BUNDLE", "STRIPE_ISSUING_CARD_LOGO"},
		"issuing_personalization_design_default_toggle",
		"stripe_issuing_personalization_design",
		"stripe_issuing_personalization_design.test",
		"issuing_personalization_design_default_toggle_create.tf",
		"issuing_personalization_design_default_toggle_update.tf",
		true,
		verifyIssuingPersonalizationDesign(issuingPersonalizationDesignExpectations{
			Address:               "stripe_issuing_personalization_design.test",
			ExpectedName:          "SDK Codegen Design Default Create",
			CompareStateLookupKey: true,
			CheckCarrierText:      true,
			ExpectedHeaderTitle:   "SDK Default",
			ExpectedHeaderBody:    "Create",
			ExpectedFooterTitle:   "Desk",
			ExpectedFooterBody:    "create@example.com",
			CheckIsDefault:        true,
			ExpectedIsDefault:     true,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_personalization_design_default_toggle",
				"phase": "create",
			},
		}),
		verifyIssuingPersonalizationDesign(issuingPersonalizationDesignExpectations{
			Address:               "stripe_issuing_personalization_design.test",
			ExpectedName:          "SDK Codegen Design Default Update",
			CompareStateLookupKey: true,
			CheckCarrierText:      true,
			ExpectedHeaderTitle:   "SDK Default",
			ExpectedHeaderBody:    "Create",
			ExpectedFooterTitle:   "Desk",
			ExpectedFooterBody:    "create@example.com",
			CheckIsDefault:        true,
			ExpectedIsDefault:     false,
			ExpectedMetadata: map[string]string{
				"suite": "sdk-codegen",
				"case":  "issuing_personalization_design_default_toggle",
				"phase": "update",
			},
		}),
		verifyIssuingPersonalizationDesignDestroyStillExists,
	)
}
