// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"strconv"
	"strings"

	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"reflect"
)

// normalizeDecimalString removes unnecessary trailing zeros from decimal strings
// This prevents Terraform drift when API returns "0.0015000000" but user specified "0.0015"
func normalizeDecimalString(s string) string {
	if s == "" {
		return s
	}
	// Only process if there's a decimal point
	if !strings.Contains(s, ".") {
		return s
	}
	// Remove trailing zeros after decimal point
	s = strings.TrimRight(s, "0")
	// Remove trailing decimal point if no fractional part remains
	s = strings.TrimSuffix(s, ".")
	return s
}

// normalizeDecimalFloat converts a float64 to a normalized decimal string
// This handles SDK fields that are float64 but represented as strings in Terraform
func normalizeDecimalFloat(f float64) string {
	s := strconv.FormatFloat(f, 'f', -1, 64)
	return normalizeDecimalString(s)
}

// suppressDecimalDiff compares decimal strings after normalization
// This prevents false diffs when config has "0.0012500000" but state has "0.00125"
func suppressDecimalDiff(k, old, new string, d *schema.ResourceData) bool {
	return normalizeDecimalString(old) == normalizeDecimalString(new)
}

// paramsHasFields checks if a params struct has any non-nil fields
// This is used to detect if Update should be called or skipped when all changes are field removals
func paramsHasFields(params interface{}) bool {
	if params == nil {
		return false
	}
	v := reflect.ValueOf(params)
	// Dereference pointer if needed
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return false
	}
	// Check each field to see if any are non-nil
	for i := 0; i < v.NumField(); i++ {
		field := v.Field(i)
		// Check if field is a pointer and not nil
		if field.Kind() == reflect.Ptr && !field.IsNil() {
			return true
		}
		// Check if field is a map and not empty
		if field.Kind() == reflect.Map && field.Len() > 0 {
			return true
		}
		// Check if field is a slice and not empty
		if field.Kind() == reflect.Slice && field.Len() > 0 {
			return true
		}
	}
	return false
}
