// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"reflect"
	"strconv"
	"strings"
)

// normalizeDecimalString removes unnecessary trailing .0 from decimal strings
// This prevents Terraform drift when API returns "2000.0" but user specified "2000"
func normalizeDecimalString(s string) string {
	if strings.HasSuffix(s, ".0") {
		return strings.TrimSuffix(s, ".0")
	}
	return s
}

// normalizeDecimalFloat converts a float64 to a normalized decimal string
// This handles SDK fields that are float64 but represented as strings in Terraform
func normalizeDecimalFloat(f float64) string {
	s := strconv.FormatFloat(f, 'f', -1, 64)
	return normalizeDecimalString(s)
}

// paramsHasFields checks if a params struct has any non-nil fields
// This is used to detect if Update should be called or skipped when all changes are field removals
func paramsHasFields(params interface{}) bool {
	if params == nil {
		return false
	}
	v := reflect.ValueOf(params)
	// Dereference pointer if needed
	if v.Kind() == reflect.Ptr {
		v = v.Elem()
	}
	if v.Kind() != reflect.Struct {
		return false
	}
	// Check each field to see if any are non-nil
	for i := 0; i < v.NumField(); i++ {
		field := v.Field(i)
		// Check if field is a pointer and not nil
		if field.Kind() == reflect.Ptr && !field.IsNil() {
			return true
		}
		// Check if field is a map and not empty
		if field.Kind() == reflect.Map && field.Len() > 0 {
			return true
		}
		// Check if field is a slice and not empty
		if field.Kind() == reflect.Slice && field.Len() > 0 {
			return true
		}
	}
	return false
}
