// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2CoreEventDestination returns the schema for the stripe_v2_core_event_destination resource
func ResourceV2CoreEventDestination() *schema.Resource {
	return &schema.Resource{
		Description: "Set up an event destination to receive events from Stripe across multiple destination types, including [webhook endpoints](https://docs.stripe.com/webhooks) and [Amazon EventBridge](https://docs.stripe.com/event-destinations/eventbridge). Event destinations support receiving [thin events](https://docs.stripe.com/api/v2/events) and [snapshot events](https://docs.stripe.com/api/events).",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"description": {
				Type:        schema.TypeString,
				Description: "An optional description of what the event destination is used for.",
				Optional:    true,
				Computed:    true,
			},
			"enabled_events": {
				Type:        schema.TypeList,
				Description: "The list of events to enable for this endpoint.",
				Required:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"event_payload": {
				Type:        schema.TypeString,
				Description: "Payload type of events being subscribed to.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"snapshot",
					"thin",
				}, false)),
			},
			"events_from": {
				Type:        schema.TypeList,
				Description: "Where events should be routed from.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Metadata.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"name": {
				Type:        schema.TypeString,
				Description: "Event destination name.",
				Required:    true,
			},
			"snapshot_api_version": {
				Type:        schema.TypeString,
				Description: "If using the snapshot event payload, the API version events are rendered as.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
			},
			"type": {
				Type:        schema.TypeString,
				Description: "Event destination type.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"amazon_eventbridge",
					"webhook_endpoint",
				}, false)),
			},
			"amazon_eventbridge": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "Amazon EventBridge configuration.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"aws_account_id": {
							Type:        schema.TypeString,
							Description: "The AWS account ID.",
							Required:    true,
							ForceNew:    true,
						},
						"aws_region": {
							Type:        schema.TypeString,
							Description: "The region of the AWS event source.",
							Required:    true,
							ForceNew:    true,
						},
					},
				},
			},
			"webhook_endpoint": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				Description: "Webhook endpoint configuration.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"url": {
							Type:        schema.TypeString,
							Description: "The URL of the webhook endpoint.",
							Required:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceV2CoreEventDestinationCreate,
		ReadContext:   resourceV2CoreEventDestinationRead,
		UpdateContext: resourceV2CoreEventDestinationUpdate,
		DeleteContext: resourceV2CoreEventDestinationDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2CoreEventDestinationCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_core_event_destination resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2CoreEventDestinationCreateParams{}

	if v, ok := d.Get("description").(string); ok && v != "" {
		params.Description = stripe.String(v)
	}
	if v, ok := d.Get("enabled_events").([]interface{}); ok && len(v) > 0 {
		strArr := make([]*string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				strArr[i] = stripe.String(s)
			}
		}
		params.EnabledEvents = strArr
	}
	if v, ok := d.Get("event_payload").(string); ok && v != "" {
		params.EventPayload = stripe.String(v)
	}
	if v, ok := d.Get("events_from").([]interface{}); ok && len(v) > 0 {
		strArr := make([]*string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				strArr[i] = stripe.String(s)
			}
		}
		params.EventsFrom = strArr
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("name").(string); ok && v != "" {
		params.Name = stripe.String(v)
	}
	if v, ok := d.Get("snapshot_api_version").(string); ok && v != "" {
		params.SnapshotAPIVersion = stripe.String(v)
	}
	if v, ok := d.Get("type").(string); ok && v != "" {
		params.Type = stripe.String(v)
	}
	if v, ok := d.Get("amazon_eventbridge").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.AmazonEventbridge = &stripe.V2CoreEventDestinationCreateAmazonEventbridgeParams{}
		if val, ok := data["aws_account_id"].(string); ok && val != "" {
			params.AmazonEventbridge.AwsAccountID = stripe.String(val)
		}
		if val, ok := data["aws_region"].(string); ok && val != "" {
			params.AmazonEventbridge.AwsRegion = stripe.String(val)
		}
	}
	if v, ok := d.Get("webhook_endpoint").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.WebhookEndpoint = &stripe.V2CoreEventDestinationCreateWebhookEndpointParams{}
		if val, ok := data["url"].(string); ok && val != "" {
			params.WebhookEndpoint.URL = stripe.String(val)
		}
	}
	v2_core_event_destination, err := c.V2CoreEventDestinations.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_core_event_destination: %w", err))
	}

	d.SetId(v2_core_event_destination.ID)
	return resourceV2CoreEventDestinationRead(ctx, d, meta)
}

func resourceV2CoreEventDestinationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_core_event_destination resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	v2_core_event_destination, err := c.V2CoreEventDestinations.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_core_event_destination: %w", err))
	}

	if err := d.Set("description", v2_core_event_destination.Description); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if v2_core_event_destination.EnabledEvents != nil && len(v2_core_event_destination.EnabledEvents) > 0 {
		if err := d.Set("enabled_events", v2_core_event_destination.EnabledEvents); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("event_payload", v2_core_event_destination.EventPayload); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	// Always set events_from (Computed + ForceNew) to prevent unnecessary replacements
	if v2_core_event_destination.EventsFrom != nil {
		if err := d.Set("events_from", v2_core_event_destination.EventsFrom); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	} else {
		if err := d.Set("events_from", []string{}); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("metadata", v2_core_event_destination.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("name", v2_core_event_destination.Name); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("snapshot_api_version", v2_core_event_destination.SnapshotAPIVersion); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("type", v2_core_event_destination.Type); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if _, ok := d.GetOk("amazon_eventbridge"); ok {
		if v2_core_event_destination.AmazonEventbridge != nil {
			nestedData := make(map[string]interface{})
			nestedData["aws_account_id"] = v2_core_event_destination.AmazonEventbridge.AwsAccountID
			nestedData["aws_event_source_arn"] = v2_core_event_destination.AmazonEventbridge.AwsEventSourceArn
			nestedData["aws_event_source_status"] = v2_core_event_destination.AmazonEventbridge.AwsEventSourceStatus
			if len(nestedData) > 0 {
				if err := d.Set("amazon_eventbridge", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if _, ok := d.GetOk("webhook_endpoint"); ok {
		if v2_core_event_destination.WebhookEndpoint != nil {
			nestedData := make(map[string]interface{})
			if v2_core_event_destination.WebhookEndpoint.SigningSecret != "" {
				nestedData["signing_secret"] = v2_core_event_destination.WebhookEndpoint.SigningSecret
			}
			if v2_core_event_destination.WebhookEndpoint.URL != "" {
				nestedData["url"] = v2_core_event_destination.WebhookEndpoint.URL
			}
			if len(nestedData) > 0 {
				if err := d.Set("webhook_endpoint", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	return diags
}

func resourceV2CoreEventDestinationUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_v2_core_event_destination resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2CoreEventDestinationUpdateParams{}

	if d.HasChange("description") {
		if v, ok := d.Get("description").(string); ok && v != "" {
			params.Description = stripe.String(v)
		}
	}
	if d.HasChange("enabled_events") {
		if v, ok := d.Get("enabled_events").([]interface{}); ok && len(v) > 0 {
			strArr := make([]*string, len(v))
			for i, item := range v {
				if s, ok := item.(string); ok {
					strArr[i] = stripe.String(s)
				}
			}
			params.EnabledEvents = strArr
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions (V2 uses *string)
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]*string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = stripe.String(v.(string))
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = stripe.String("")
			}
		}
	}
	if d.HasChange("name") {
		if v, ok := d.Get("name").(string); ok && v != "" {
			params.Name = stripe.String(v)
		}
	}
	if d.HasChange("webhook_endpoint") {
		if v, ok := d.Get("webhook_endpoint").([]interface{}); ok && len(v) > 0 {
			data := v[0].(map[string]interface{})
			params.WebhookEndpoint = &stripe.V2CoreEventDestinationUpdateWebhookEndpointParams{}
			if val, ok := data["url"].(string); ok && val != "" {
				params.WebhookEndpoint.URL = stripe.String(val)
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceV2CoreEventDestinationRead(ctx, d, meta)
	}

	_, err := c.V2CoreEventDestinations.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update v2_core_event_destination: %w", err))
	}

	return resourceV2CoreEventDestinationRead(ctx, d, meta)
}

func resourceV2CoreEventDestinationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Deleting stripe_v2_core_event_destination resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	_, err := c.V2CoreEventDestinations.Delete(ctx, d.Id(), nil)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to delete v2_core_event_destination: %w", err))
	}

	d.SetId("")
	return nil
}
