// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceBillingPortalConfiguration returns the schema for the stripe_billing_portal_configuration resource
func ResourceBillingPortalConfiguration() *schema.Resource {
	return &schema.Resource{
		Description: "A portal configuration describes the functionality and behavior you embed in a portal session. Related guide: [Configure the customer portal](/customer-management/configure-portal).",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"default_return_url": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"name": {
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
			},
			"active": {
				Type:        schema.TypeBool,
				Description: "Whether the configuration is active and can be used to create portal sessions.",
				Computed:    true,
			},
			"is_default": {
				Type:        schema.TypeBool,
				Description: "Whether the configuration is the default. If `true`, this configuration can be managed in the Dashboard and portal sessions will use this configuration unless it is overriden when creating the session.",
				Computed:    true,
			},
			"business_profile": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				Description: "The business information shown to customers in the portal.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"headline": {
							Type:     schema.TypeString,
							Optional: true,
						},
						"privacy_policy_url": {
							Type:        schema.TypeString,
							Description: "A link to the business’s publicly available privacy policy.",
							Optional:    true,
						},
						"terms_of_service_url": {
							Type:        schema.TypeString,
							Description: "A link to the business’s publicly available terms of service.",
							Optional:    true,
						},
					},
				},
			},
			"features": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Required:    true,
				Description: "Information about the features available in the portal.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"customer_update": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Information about updating the customer details in the portal.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"allowed_updates": {
										Type:     schema.TypeList,
										Optional: true,
										Elem:     &schema.Schema{Type: schema.TypeString},
									},
									"enabled": {
										Type:        schema.TypeBool,
										Description: "Whether the feature is enabled.",
										Required:    true,
									},
								},
							},
						},
						"invoice_history": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Information about showing the billing history in the portal.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"enabled": {
										Type:        schema.TypeBool,
										Description: "Whether the feature is enabled.",
										Required:    true,
									},
								},
							},
						},
						"payment_method_update": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Information about updating payment methods in the portal.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"enabled": {
										Type:        schema.TypeBool,
										Description: "Whether the feature is enabled.",
										Required:    true,
									},
									"payment_method_configuration": {
										Type:     schema.TypeString,
										Optional: true,
									},
								},
							},
						},
						"subscription_cancel": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Information about canceling subscriptions in the portal.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"cancellation_reason": {
										Type:        schema.TypeList,
										MaxItems:    1,
										Optional:    true,
										Description: "Whether the cancellation reasons will be collected in the portal and which options are exposed to the customer",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"enabled": {
													Type:        schema.TypeBool,
													Description: "Whether the feature is enabled.",
													Required:    true,
												},
												"options": {
													Type:     schema.TypeList,
													Required: true,
													Elem:     &schema.Schema{Type: schema.TypeString},
												},
											},
										},
									},
									"enabled": {
										Type:        schema.TypeBool,
										Description: "Whether the feature is enabled.",
										Required:    true,
									},
									"mode": {
										Type:        schema.TypeString,
										Description: "Whether to cancel subscriptions immediately or at the end of the billing period.",
										Optional:    true,
										ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
											"at_period_end",
											"immediately",
										}, false)),
									},
									"proration_behavior": {
										Type:        schema.TypeString,
										Description: "Whether to create prorations when canceling subscriptions. Possible values are `none` and `create_prorations`, which is only compatible with `mode=immediately`. Passing `always_invoice` will result in an error. No prorations are generated when canceling a subscription at the end of its natural billing period.",
										Optional:    true,
										ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
											"always_invoice",
											"create_prorations",
											"none",
										}, false)),
									},
								},
							},
						},
						"subscription_update": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "Information about updating subscriptions in the portal.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"default_allowed_updates": {
										Type:     schema.TypeList,
										Optional: true,
										Elem:     &schema.Schema{Type: schema.TypeString},
									},
									"enabled": {
										Type:        schema.TypeBool,
										Description: "Whether the feature is enabled.",
										Required:    true,
									},
									"products": {
										Type:     schema.TypeList,
										Optional: true,
										Elem:     &schema.Schema{Type: schema.TypeList},
									},
									"proration_behavior": {
										Type:        schema.TypeString,
										Description: "Determines how to handle prorations resulting from subscription updates. Valid values are `none`, `create_prorations`, and `always_invoice`.",
										Optional:    true,
										ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
											"always_invoice",
											"create_prorations",
											"none",
										}, false)),
									},
									"schedule_at_period_end": {
										Type:        schema.TypeList,
										MaxItems:    1,
										Optional:    true,
										Description: "Setting to control when an update should be scheduled at the end of the period instead of applying immediately.",
										Elem: &schema.Resource{
											Schema: map[string]*schema.Schema{
												"conditions": {
													Type:        schema.TypeList,
													Description: "List of conditions. When any condition is true, the update will be scheduled at the end of the current period.",
													Optional:    true,
													Elem:        &schema.Schema{Type: schema.TypeList},
												},
											},
										},
									},
									"trial_update_behavior": {
										Type:        schema.TypeString,
										Description: "The behavior when updating a subscription that is trialing.",
										Optional:    true,
										ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
											"continue_trial",
											"end_trial",
										}, false)),
									},
								},
							},
						},
					},
				},
			},
			"login_page": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				Description: "The hosted login page for this configuration. Learn more about the portal login page in our [integration docs](https://stripe.com/docs/billing/subscriptions/integrating-customer-portal#share).",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"enabled": {
							Type:        schema.TypeBool,
							Description: "Set to `true` to generate a shareable URL [`login_page.url`](https://stripe.com/docs/api/customer_portal/configuration#portal_configuration_object-login_page-url) that will take your customers to a hosted login page for the customer portal.",
							Required:    true,
						},
						"url": {
							Type:        schema.TypeString,
							Description: "A shareable URL to the hosted portal login page. Your customers will be able to log in with their [email](https://stripe.com/docs/api/customers/object#customer_object-email) and receive a link to their customer portal.",
							Computed:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceBillingPortalConfigurationCreate,
		ReadContext:   resourceBillingPortalConfigurationRead,
		UpdateContext: resourceBillingPortalConfigurationUpdate,
		DeleteContext: resourceBillingPortalConfigurationDelete,

		Importer: &schema.ResourceImporter{
			StateContext: resourceBillingPortalConfigurationImportState,
		},
	}
}

func resourceBillingPortalConfigurationCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_billing_portal_configuration resource")
	c := meta.(*stripe.Client)

	params := &stripe.BillingPortalConfigurationCreateParams{}

	if v, ok := d.Get("default_return_url").(string); ok && v != "" {
		params.DefaultReturnURL = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("name").(string); ok && v != "" {
		params.Name = stripe.String(v)
	}
	if v, ok := d.Get("business_profile").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.BusinessProfile = &stripe.BillingPortalConfigurationCreateBusinessProfileParams{}
		if val, ok := data["headline"].(string); ok && val != "" {
			params.BusinessProfile.Headline = stripe.String(val)
		}
		if val, ok := data["privacy_policy_url"].(string); ok && val != "" {
			params.BusinessProfile.PrivacyPolicyURL = stripe.String(val)
		}
		if val, ok := data["terms_of_service_url"].(string); ok && val != "" {
			params.BusinessProfile.TermsOfServiceURL = stripe.String(val)
		}
	}
	if v, ok := d.Get("features").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.Features = &stripe.BillingPortalConfigurationCreateFeaturesParams{}
		if v, ok := data["customer_update"].([]interface{}); ok && len(v) > 0 {
			nestedData0 := v[0].(map[string]interface{})
			params.Features.CustomerUpdate = &stripe.BillingPortalConfigurationCreateFeaturesCustomerUpdateParams{}
			if val, ok := nestedData0["allowed_updates"].([]interface{}); ok && len(val) > 0 {
				strArr := make([]*string, len(val))
				for i, v := range val {
					if s, ok := v.(string); ok {
						strArr[i] = stripe.String(s)
					}
				}
				params.Features.CustomerUpdate.AllowedUpdates = strArr
			}
			if val, ok := nestedData0["enabled"].(bool); ok {
				params.Features.CustomerUpdate.Enabled = stripe.Bool(val)
			}
		}
		if v, ok := data["invoice_history"].([]interface{}); ok && len(v) > 0 {
			nestedData0 := v[0].(map[string]interface{})
			params.Features.InvoiceHistory = &stripe.BillingPortalConfigurationCreateFeaturesInvoiceHistoryParams{}
			if val, ok := nestedData0["enabled"].(bool); ok {
				params.Features.InvoiceHistory.Enabled = stripe.Bool(val)
			}
		}
		if v, ok := data["payment_method_update"].([]interface{}); ok && len(v) > 0 {
			nestedData0 := v[0].(map[string]interface{})
			params.Features.PaymentMethodUpdate = &stripe.BillingPortalConfigurationCreateFeaturesPaymentMethodUpdateParams{}
			if val, ok := nestedData0["enabled"].(bool); ok {
				params.Features.PaymentMethodUpdate.Enabled = stripe.Bool(val)
			}
			if val, ok := nestedData0["payment_method_configuration"].(string); ok && val != "" {
				params.Features.PaymentMethodUpdate.PaymentMethodConfiguration = stripe.String(val)
			}
		}
		if v, ok := data["subscription_cancel"].([]interface{}); ok && len(v) > 0 {
			nestedData0 := v[0].(map[string]interface{})
			params.Features.SubscriptionCancel = &stripe.BillingPortalConfigurationCreateFeaturesSubscriptionCancelParams{}
			if v, ok := nestedData0["cancellation_reason"].([]interface{}); ok && len(v) > 0 {
				nestedData1 := v[0].(map[string]interface{})
				params.Features.SubscriptionCancel.CancellationReason = &stripe.BillingPortalConfigurationCreateFeaturesSubscriptionCancelCancellationReasonParams{}
				if val, ok := nestedData1["enabled"].(bool); ok {
					params.Features.SubscriptionCancel.CancellationReason.Enabled = stripe.Bool(val)
				}
				if val, ok := nestedData1["options"].([]interface{}); ok && len(val) > 0 {
					strArr := make([]*string, len(val))
					for i, v := range val {
						if s, ok := v.(string); ok {
							strArr[i] = stripe.String(s)
						}
					}
					params.Features.SubscriptionCancel.CancellationReason.Options = strArr
				}
			}
			if val, ok := nestedData0["enabled"].(bool); ok {
				params.Features.SubscriptionCancel.Enabled = stripe.Bool(val)
			}
			if val, ok := nestedData0["mode"].(string); ok && val != "" {
				params.Features.SubscriptionCancel.Mode = stripe.String(val)
			}
			if val, ok := nestedData0["proration_behavior"].(string); ok && val != "" {
				params.Features.SubscriptionCancel.ProrationBehavior = stripe.String(val)
			}
		}
		if v, ok := data["subscription_update"].([]interface{}); ok && len(v) > 0 {
			nestedData0 := v[0].(map[string]interface{})
			params.Features.SubscriptionUpdate = &stripe.BillingPortalConfigurationCreateFeaturesSubscriptionUpdateParams{}
			if val, ok := nestedData0["default_allowed_updates"].([]interface{}); ok && len(val) > 0 {
				strArr := make([]*string, len(val))
				for i, v := range val {
					if s, ok := v.(string); ok {
						strArr[i] = stripe.String(s)
					}
				}
				params.Features.SubscriptionUpdate.DefaultAllowedUpdates = strArr
			}
			if val, ok := nestedData0["enabled"].(bool); ok {
				params.Features.SubscriptionUpdate.Enabled = stripe.Bool(val)
			}
			if val, ok := nestedData0["products"].([]interface{}); ok && len(val) > 0 {
				// TODO: Handle complex array conversion for products
			}
			if val, ok := nestedData0["proration_behavior"].(string); ok && val != "" {
				params.Features.SubscriptionUpdate.ProrationBehavior = stripe.String(val)
			}
			if v, ok := nestedData0["schedule_at_period_end"].([]interface{}); ok && len(v) > 0 {
				nestedData1 := v[0].(map[string]interface{})
				params.Features.SubscriptionUpdate.ScheduleAtPeriodEnd = &stripe.BillingPortalConfigurationCreateFeaturesSubscriptionUpdateScheduleAtPeriodEndParams{}
				if val, ok := nestedData1["conditions"].([]interface{}); ok && len(val) > 0 {
					// TODO: Handle complex array conversion for conditions
				}
			}
			if val, ok := nestedData0["trial_update_behavior"].(string); ok && val != "" {
				params.Features.SubscriptionUpdate.TrialUpdateBehavior = stripe.String(val)
			}
		}
	}
	if v, ok := d.Get("login_page").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.LoginPage = &stripe.BillingPortalConfigurationCreateLoginPageParams{}
		if val, ok := data["enabled"].(bool); ok {
			params.LoginPage.Enabled = stripe.Bool(val)
		}
	}
	billing_portal_configuration, err := c.V1BillingPortalConfigurations.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create billing_portal_configuration: %w", err))
	}

	d.SetId(billing_portal_configuration.ID)
	return resourceBillingPortalConfigurationRead(ctx, d, meta)
}

func resourceBillingPortalConfigurationRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	importing := ctx.Value("importing") != nil
	_ = importing
	tflog.Debug(ctx, "Reading stripe_billing_portal_configuration resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	billing_portal_configuration, err := c.V1BillingPortalConfigurations.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read billing_portal_configuration: %w", err))
	}

	if err := d.Set("default_return_url", billing_portal_configuration.DefaultReturnURL); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", billing_portal_configuration.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("name", billing_portal_configuration.Name); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("active", billing_portal_configuration.Active); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("is_default", billing_portal_configuration.IsDefault); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if _, ok := d.GetOk("business_profile"); importing || ok {
		if billing_portal_configuration.BusinessProfile != nil {
			nestedData := make(map[string]interface{})
			if billing_portal_configuration.BusinessProfile.Headline != "" {
				nestedData["headline"] = billing_portal_configuration.BusinessProfile.Headline
			}
			if billing_portal_configuration.BusinessProfile.PrivacyPolicyURL != "" {
				nestedData["privacy_policy_url"] = billing_portal_configuration.BusinessProfile.PrivacyPolicyURL
			}
			if billing_portal_configuration.BusinessProfile.TermsOfServiceURL != "" {
				nestedData["terms_of_service_url"] = billing_portal_configuration.BusinessProfile.TermsOfServiceURL
			}
			if len(nestedData) > 0 {
				if err := d.Set("business_profile", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if billing_portal_configuration.Features != nil {
		nestedData := make(map[string]interface{})
		if _, ok := d.GetOk("features.0.customer_update"); importing || ok {
			if billing_portal_configuration.Features.CustomerUpdate != nil {
				nestedData0 := make(map[string]interface{})
				if len(billing_portal_configuration.Features.CustomerUpdate.AllowedUpdates) > 0 {
					arrAllowedUpdates1 := make([]interface{}, len(billing_portal_configuration.Features.CustomerUpdate.AllowedUpdates))
					for i, v := range billing_portal_configuration.Features.CustomerUpdate.AllowedUpdates {
						arrAllowedUpdates1[i] = string(v)
					}
					nestedData0["allowed_updates"] = arrAllowedUpdates1
				}
				nestedData0["enabled"] = billing_portal_configuration.Features.CustomerUpdate.Enabled
				nestedData["customer_update"] = []interface{}{nestedData0}
			}
		}
		if _, ok := d.GetOk("features.0.invoice_history"); importing || ok {
			if billing_portal_configuration.Features.InvoiceHistory != nil {
				nestedData0 := make(map[string]interface{})
				nestedData0["enabled"] = billing_portal_configuration.Features.InvoiceHistory.Enabled
				nestedData["invoice_history"] = []interface{}{nestedData0}
			}
		}
		if _, ok := d.GetOk("features.0.payment_method_update"); importing || ok {
			if billing_portal_configuration.Features.PaymentMethodUpdate != nil {
				nestedData0 := make(map[string]interface{})
				nestedData0["enabled"] = billing_portal_configuration.Features.PaymentMethodUpdate.Enabled
				if billing_portal_configuration.Features.PaymentMethodUpdate.PaymentMethodConfiguration != "" {
					nestedData0["payment_method_configuration"] = billing_portal_configuration.Features.PaymentMethodUpdate.PaymentMethodConfiguration
				}
				nestedData["payment_method_update"] = []interface{}{nestedData0}
			}
		}
		if _, ok := d.GetOk("features.0.subscription_cancel"); importing || ok {
			if billing_portal_configuration.Features.SubscriptionCancel != nil {
				nestedData0 := make(map[string]interface{})
				if _, ok := d.GetOk("features.0.subscription_cancel.0.cancellation_reason"); importing || ok {
					if billing_portal_configuration.Features.SubscriptionCancel.CancellationReason != nil {
						nestedData1 := make(map[string]interface{})
						nestedData1["enabled"] = billing_portal_configuration.Features.SubscriptionCancel.CancellationReason.Enabled
						if len(billing_portal_configuration.Features.SubscriptionCancel.CancellationReason.Options) > 0 {
							arrOptions2 := make([]interface{}, len(billing_portal_configuration.Features.SubscriptionCancel.CancellationReason.Options))
							for i, v := range billing_portal_configuration.Features.SubscriptionCancel.CancellationReason.Options {
								arrOptions2[i] = string(v)
							}
							nestedData1["options"] = arrOptions2
						}
						nestedData0["cancellation_reason"] = []interface{}{nestedData1}
					}
				}
				nestedData0["enabled"] = billing_portal_configuration.Features.SubscriptionCancel.Enabled
				if billing_portal_configuration.Features.SubscriptionCancel.Mode != "" {
					nestedData0["mode"] = billing_portal_configuration.Features.SubscriptionCancel.Mode
				}
				if billing_portal_configuration.Features.SubscriptionCancel.ProrationBehavior != "" {
					nestedData0["proration_behavior"] = billing_portal_configuration.Features.SubscriptionCancel.ProrationBehavior
				}
				nestedData["subscription_cancel"] = []interface{}{nestedData0}
			}
		}
		if _, ok := d.GetOk("features.0.subscription_update"); importing || ok {
			if billing_portal_configuration.Features.SubscriptionUpdate != nil {
				nestedData0 := make(map[string]interface{})
				if len(billing_portal_configuration.Features.SubscriptionUpdate.DefaultAllowedUpdates) > 0 {
					arrDefaultAllowedUpdates1 := make([]interface{}, len(billing_portal_configuration.Features.SubscriptionUpdate.DefaultAllowedUpdates))
					for i, v := range billing_portal_configuration.Features.SubscriptionUpdate.DefaultAllowedUpdates {
						arrDefaultAllowedUpdates1[i] = string(v)
					}
					nestedData0["default_allowed_updates"] = arrDefaultAllowedUpdates1
				}
				nestedData0["enabled"] = billing_portal_configuration.Features.SubscriptionUpdate.Enabled
				if billing_portal_configuration.Features.SubscriptionUpdate.ProrationBehavior != "" {
					nestedData0["proration_behavior"] = billing_portal_configuration.Features.SubscriptionUpdate.ProrationBehavior
				}
				if _, ok := d.GetOk("features.0.subscription_update.0.schedule_at_period_end"); importing || ok {
					if billing_portal_configuration.Features.SubscriptionUpdate.ScheduleAtPeriodEnd != nil {
						nestedData1 := make(map[string]interface{})
						nestedData0["schedule_at_period_end"] = []interface{}{nestedData1}
					}
				}
				if billing_portal_configuration.Features.SubscriptionUpdate.TrialUpdateBehavior != "" {
					nestedData0["trial_update_behavior"] = billing_portal_configuration.Features.SubscriptionUpdate.TrialUpdateBehavior
				}
				nestedData["subscription_update"] = []interface{}{nestedData0}
			}
		}
		if len(nestedData) > 0 {
			if err := d.Set("features", []interface{}{nestedData}); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	if _, ok := d.GetOk("login_page"); importing || ok {
		if billing_portal_configuration.LoginPage != nil {
			nestedData := make(map[string]interface{})
			nestedData["enabled"] = billing_portal_configuration.LoginPage.Enabled
			if billing_portal_configuration.LoginPage.URL != "" {
				nestedData["url"] = billing_portal_configuration.LoginPage.URL
			}
			if len(nestedData) > 0 {
				if err := d.Set("login_page", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	return diags
}

func resourceBillingPortalConfigurationUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_billing_portal_configuration resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.BillingPortalConfigurationUpdateParams{}

	if d.HasChange("default_return_url") {
		if v, ok := d.Get("default_return_url").(string); ok && v != "" {
			params.DefaultReturnURL = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = v.(string)
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = ""
			}
		}
	}
	if d.HasChange("name") {
		if v, ok := d.Get("name").(string); ok && v != "" {
			params.Name = stripe.String(v)
		}
	}
	if d.HasChange("business_profile") {
		if v, ok := d.Get("business_profile").([]interface{}); ok && len(v) > 0 {
			data := v[0].(map[string]interface{})
			params.BusinessProfile = &stripe.BillingPortalConfigurationUpdateBusinessProfileParams{}
			if val, ok := data["headline"].(string); ok && val != "" {
				params.BusinessProfile.Headline = stripe.String(val)
			}
			if val, ok := data["privacy_policy_url"].(string); ok && val != "" {
				params.BusinessProfile.PrivacyPolicyURL = stripe.String(val)
			}
			if val, ok := data["terms_of_service_url"].(string); ok && val != "" {
				params.BusinessProfile.TermsOfServiceURL = stripe.String(val)
			}
		}
	}
	if d.HasChange("features") {
		if v, ok := d.Get("features").([]interface{}); ok && len(v) > 0 {
			data := v[0].(map[string]interface{})
			params.Features = &stripe.BillingPortalConfigurationUpdateFeaturesParams{}
			if v, ok := data["customer_update"].([]interface{}); ok && len(v) > 0 {
				nestedData0 := v[0].(map[string]interface{})
				params.Features.CustomerUpdate = &stripe.BillingPortalConfigurationUpdateFeaturesCustomerUpdateParams{}
				if val, ok := nestedData0["enabled"].(bool); ok {
					params.Features.CustomerUpdate.Enabled = stripe.Bool(val)
				}
			}
			if v, ok := data["invoice_history"].([]interface{}); ok && len(v) > 0 {
				nestedData0 := v[0].(map[string]interface{})
				params.Features.InvoiceHistory = &stripe.BillingPortalConfigurationUpdateFeaturesInvoiceHistoryParams{}
				if val, ok := nestedData0["enabled"].(bool); ok {
					params.Features.InvoiceHistory.Enabled = stripe.Bool(val)
				}
			}
			if v, ok := data["payment_method_update"].([]interface{}); ok && len(v) > 0 {
				nestedData0 := v[0].(map[string]interface{})
				params.Features.PaymentMethodUpdate = &stripe.BillingPortalConfigurationUpdateFeaturesPaymentMethodUpdateParams{}
				if val, ok := nestedData0["enabled"].(bool); ok {
					params.Features.PaymentMethodUpdate.Enabled = stripe.Bool(val)
				}
				if val, ok := nestedData0["payment_method_configuration"].(string); ok && val != "" {
					params.Features.PaymentMethodUpdate.PaymentMethodConfiguration = stripe.String(val)
				}
			}
			if v, ok := data["subscription_cancel"].([]interface{}); ok && len(v) > 0 {
				nestedData0 := v[0].(map[string]interface{})
				params.Features.SubscriptionCancel = &stripe.BillingPortalConfigurationUpdateFeaturesSubscriptionCancelParams{}
				if val, ok := nestedData0["enabled"].(bool); ok {
					params.Features.SubscriptionCancel.Enabled = stripe.Bool(val)
				}
				if val, ok := nestedData0["mode"].(string); ok && val != "" {
					params.Features.SubscriptionCancel.Mode = stripe.String(val)
				}
				if val, ok := nestedData0["proration_behavior"].(string); ok && val != "" {
					params.Features.SubscriptionCancel.ProrationBehavior = stripe.String(val)
				}
			}
			if v, ok := data["subscription_update"].([]interface{}); ok && len(v) > 0 {
				nestedData0 := v[0].(map[string]interface{})
				params.Features.SubscriptionUpdate = &stripe.BillingPortalConfigurationUpdateFeaturesSubscriptionUpdateParams{}
				if val, ok := nestedData0["enabled"].(bool); ok {
					params.Features.SubscriptionUpdate.Enabled = stripe.Bool(val)
				}
				if val, ok := nestedData0["proration_behavior"].(string); ok && val != "" {
					params.Features.SubscriptionUpdate.ProrationBehavior = stripe.String(val)
				}
				if val, ok := nestedData0["trial_update_behavior"].(string); ok && val != "" {
					params.Features.SubscriptionUpdate.TrialUpdateBehavior = stripe.String(val)
				}
			}
		}
	}
	if d.HasChange("login_page") {
		if v, ok := d.Get("login_page").([]interface{}); ok && len(v) > 0 {
			data := v[0].(map[string]interface{})
			params.LoginPage = &stripe.BillingPortalConfigurationUpdateLoginPageParams{}
			if val, ok := data["enabled"].(bool); ok {
				params.LoginPage.Enabled = stripe.Bool(val)
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceBillingPortalConfigurationRead(ctx, d, meta)
	}

	_, err := c.V1BillingPortalConfigurations.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update billing_portal_configuration: %w", err))
	}

	return resourceBillingPortalConfigurationRead(ctx, d, meta)
}

func resourceBillingPortalConfigurationDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Warn(ctx, "stripe_billing_portal_configuration resources cannot be deleted via the Stripe API. "+
		"The resource will be removed from Terraform state but will remain in your Stripe account. "+
		"You may need to archive or deactivate it manually.",
		map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}

func resourceBillingPortalConfigurationImportState(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	diags := resourceBillingPortalConfigurationRead(context.WithValue(ctx, "importing", true), d, meta)
	if diags.HasError() {
		return nil, fmt.Errorf("%s", diags[0].Summary)
	}

	return []*schema.ResourceData{d}, nil
}
