// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceTaxRate returns the schema for the stripe_tax_rate resource
func ResourceTaxRate() *schema.Resource {
	return &schema.Resource{
		Description: "Tax rates can be applied to [invoices](/invoicing/taxes/tax-rates), [subscriptions](/billing/taxes/tax-rates) and [Checkout Sessions](/payments/checkout/use-manual-tax-rates) to collect tax. Related guide: [Tax rates](/billing/taxes/tax-rates)",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"active": {
				Type:        schema.TypeBool,
				Description: "Flag determining whether the tax rate is active or inactive (archived). Inactive tax rates cannot be used with new applications or Checkout Sessions, but will still work for subscriptions and invoices that already have it set.",
				Optional:    true,
				Computed:    true,
			},
			"country": {
				Type:        schema.TypeString,
				Description: "Two-letter country code ([ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2)).",
				Optional:    true,
				Computed:    true,
			},
			"description": {
				Type:        schema.TypeString,
				Description: "An arbitrary string attached to the tax rate for your internal use only. It will not be visible to your customers.",
				Optional:    true,
				Computed:    true,
			},
			"display_name": {
				Type:        schema.TypeString,
				Description: "The display name of the tax rate, which will be shown to users.",
				Required:    true,
			},
			"inclusive": {
				Type:        schema.TypeBool,
				Description: "This specifies if the tax rate is inclusive or exclusive.",
				Required:    true,
				ForceNew:    true,
			},
			"jurisdiction": {
				Type:        schema.TypeString,
				Description: "The jurisdiction for the tax rate. You can use this label field for tax reporting purposes. It also appears on your customer’s invoice.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"percentage": {
				Type:        schema.TypeFloat,
				Description: "This represents the tax rate percent out of 100.",
				Required:    true,
				ForceNew:    true,
			},
			"state": {
				Type:        schema.TypeString,
				Description: "[ISO 3166-2 subdivision code](https://en.wikipedia.org/wiki/ISO_3166-2), without country prefix. For example, \\\"NY\\\" for New York, United States.",
				Optional:    true,
				Computed:    true,
			},
			"tax_type": {
				Type:        schema.TypeString,
				Description: "The high-level tax type, such as `vat` or `sales_tax`.",
				Optional:    true,
				Computed:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"amusement_tax",
					"communications_tax",
					"gst",
					"hst",
					"igst",
					"jct",
					"lease_tax",
					"pst",
					"qst",
					"retail_delivery_fee",
					"rst",
					"sales_tax",
					"service_tax",
					"vat",
				}, false)),
			},
		},

		CreateContext: resourceTaxRateCreate,
		ReadContext:   resourceTaxRateRead,
		UpdateContext: resourceTaxRateUpdate,
		DeleteContext: resourceTaxRateDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceTaxRateCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_tax_rate resource")
	c := meta.(*stripe.Client)

	params := &stripe.TaxRateCreateParams{}

	if !d.GetRawConfig().GetAttr("active").IsNull() {
		params.Active = stripe.Bool(d.Get("active").(bool))
	}
	if v, ok := d.Get("country").(string); ok && v != "" {
		params.Country = stripe.String(v)
	}
	if v, ok := d.Get("description").(string); ok && v != "" {
		params.Description = stripe.String(v)
	}
	if v, ok := d.Get("display_name").(string); ok && v != "" {
		params.DisplayName = stripe.String(v)
	}
	params.Inclusive = stripe.Bool(d.Get("inclusive").(bool))
	if v, ok := d.Get("jurisdiction").(string); ok && v != "" {
		params.Jurisdiction = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	params.Percentage = stripe.Float64(d.Get("percentage").(float64))
	if v, ok := d.Get("state").(string); ok && v != "" {
		params.State = stripe.String(v)
	}
	if v, ok := d.Get("tax_type").(string); ok && v != "" {
		params.TaxType = stripe.String(v)
	}
	tax_rate, err := c.V1TaxRates.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create tax_rate: %w", err))
	}

	d.SetId(tax_rate.ID)
	return resourceTaxRateRead(ctx, d, meta)
}

func resourceTaxRateRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_tax_rate resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	tax_rate, err := c.V1TaxRates.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read tax_rate: %w", err))
	}

	if err := d.Set("active", tax_rate.Active); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("country", tax_rate.Country); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("description", tax_rate.Description); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("display_name", tax_rate.DisplayName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("inclusive", tax_rate.Inclusive); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("jurisdiction", tax_rate.Jurisdiction); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", tax_rate.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("percentage", tax_rate.Percentage); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("state", tax_rate.State); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tax_type", tax_rate.TaxType); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	return diags
}

func resourceTaxRateUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_tax_rate resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.TaxRateUpdateParams{}

	if d.HasChange("active") {
		params.Active = stripe.Bool(d.Get("active").(bool))
	}
	if d.HasChange("country") {
		if v, ok := d.Get("country").(string); ok && v != "" {
			params.Country = stripe.String(v)
		}
	}
	if d.HasChange("description") {
		if v, ok := d.Get("description").(string); ok && v != "" {
			params.Description = stripe.String(v)
		}
	}
	if d.HasChange("display_name") {
		if v, ok := d.Get("display_name").(string); ok && v != "" {
			params.DisplayName = stripe.String(v)
		}
	}
	if d.HasChange("jurisdiction") {
		if v, ok := d.Get("jurisdiction").(string); ok && v != "" {
			params.Jurisdiction = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = v.(string)
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = ""
			}
		}
	}
	if d.HasChange("state") {
		if v, ok := d.Get("state").(string); ok && v != "" {
			params.State = stripe.String(v)
		}
	}
	if d.HasChange("tax_type") {
		if v, ok := d.Get("tax_type").(string); ok && v != "" {
			params.TaxType = stripe.String(v)
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceTaxRateRead(ctx, d, meta)
	}

	_, err := c.V1TaxRates.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update tax_rate: %w", err))
	}

	return resourceTaxRateRead(ctx, d, meta)
}

func resourceTaxRateDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Info(ctx, "Marking stripe_tax_rate as inactive instead of deleting", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.TaxRateUpdateParams{
		Active: stripe.Bool(false),
	}

	_, err := c.V1TaxRates.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to mark tax_rate as inactive: %w", err))
	}

	tflog.Info(ctx, "stripe_tax_rate marked as inactive successfully", map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
