// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceBillingMeter returns the schema for the stripe_billing_meter resource
func ResourceBillingMeter() *schema.Resource {
	return &schema.Resource{
		Description: "Meters specify how to aggregate meter events over a billing period. Meter events represent the actions that customers take in your system. Meters attach to prices and form the basis of the bill. Related guide: [Usage based billing](https://docs.stripe.com/billing/subscriptions/usage-based)",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"dimension_payload_keys": {
				Type:        schema.TypeList,
				Description: "Set of keys that will be used to group meter events by. Each key must be present in the event payload.",
				Optional:    true,
				ForceNew:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"display_name": {
				Type:        schema.TypeString,
				Description: "The meter’s name. Not visible to the customer.",
				Required:    true,
			},
			"event_name": {
				Type:        schema.TypeString,
				Description: "The name of the meter event to record usage for. Corresponds with the `event_name` field on meter events.",
				Required:    true,
				ForceNew:    true,
			},
			"event_time_window": {
				Type:        schema.TypeString,
				Description: "The time window which meter events have been pre-aggregated for, if any.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"day",
					"hour",
				}, false)),
			},
			"customer_mapping": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "Fields that specify how to map a meter event to a customer.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"event_payload_key": {
							Type:        schema.TypeString,
							Description: "The key in the meter event payload to use for mapping the event to a customer.",
							Required:    true,
							ForceNew:    true,
						},
						"type": {
							Type:        schema.TypeString,
							Description: "The method for mapping a meter event to a customer. Must be `by_id`.",
							Required:    true,
							ForceNew:    true,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
								"by_id",
							}, false)),
						},
					},
				},
			},
			"default_aggregation": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Required:    true,
				ForceNew:    true,
				Description: "The default settings to aggregate a meter's events with.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"formula": {
							Type:        schema.TypeString,
							Description: "Specifies how events are aggregated. Allowed values are `count` to count the number of events, `sum` to sum each event's value and `last` to take the last event's value in the window.",
							Required:    true,
							ForceNew:    true,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
								"count",
								"last",
								"sum",
							}, false)),
						},
					},
				},
			},
			"value_settings": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "Fields that specify how to calculate a meter event's value.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"event_payload_key": {
							Type:        schema.TypeString,
							Description: "The key in the usage event payload to use as the value for this meter. For example, if the event payload contains usage on a `bytes_used` field, then set the event_payload_key to \\\"bytes_used\\\".",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceBillingMeterCreate,
		ReadContext:   resourceBillingMeterRead,
		UpdateContext: resourceBillingMeterUpdate,
		DeleteContext: resourceBillingMeterDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceBillingMeterCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_billing_meter resource")
	c := meta.(*stripe.Client)

	params := &stripe.BillingMeterCreateParams{}

	if v, ok := d.Get("dimension_payload_keys").([]interface{}); ok && len(v) > 0 {
		strArr := make([]*string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				strArr[i] = stripe.String(s)
			}
		}
		params.DimensionPayloadKeys = strArr
	}
	if v, ok := d.Get("display_name").(string); ok && v != "" {
		params.DisplayName = stripe.String(v)
	}
	if v, ok := d.Get("event_name").(string); ok && v != "" {
		params.EventName = stripe.String(v)
	}
	if v, ok := d.Get("event_time_window").(string); ok && v != "" {
		params.EventTimeWindow = stripe.String(v)
	}
	if v, ok := d.Get("customer_mapping").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.CustomerMapping = &stripe.BillingMeterCreateCustomerMappingParams{}
		if val, ok := data["event_payload_key"].(string); ok && val != "" {
			params.CustomerMapping.EventPayloadKey = stripe.String(val)
		}
		if val, ok := data["type"].(string); ok && val != "" {
			params.CustomerMapping.Type = stripe.String(val)
		}
	}
	if v, ok := d.Get("default_aggregation").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.DefaultAggregation = &stripe.BillingMeterCreateDefaultAggregationParams{}
		if val, ok := data["formula"].(string); ok && val != "" {
			params.DefaultAggregation.Formula = stripe.String(val)
		}
	}
	if v, ok := d.Get("value_settings").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.ValueSettings = &stripe.BillingMeterCreateValueSettingsParams{}
		if val, ok := data["event_payload_key"].(string); ok && val != "" {
			params.ValueSettings.EventPayloadKey = stripe.String(val)
		}
	}
	billing_meter, err := c.V1BillingMeters.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create billing_meter: %w", err))
	}

	d.SetId(billing_meter.ID)
	return resourceBillingMeterRead(ctx, d, meta)
}

func resourceBillingMeterRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_billing_meter resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	billing_meter, err := c.V1BillingMeters.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read billing_meter: %w", err))
	}

	if billing_meter.DimensionPayloadKeys != nil && len(billing_meter.DimensionPayloadKeys) > 0 {
		if err := d.Set("dimension_payload_keys", billing_meter.DimensionPayloadKeys); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("display_name", billing_meter.DisplayName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("event_name", billing_meter.EventName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("event_time_window", billing_meter.EventTimeWindow); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if _, ok := d.GetOk("customer_mapping"); ok {
		if billing_meter.CustomerMapping != nil {
			nestedData := make(map[string]interface{})
			nestedData["event_payload_key"] = billing_meter.CustomerMapping.EventPayloadKey
			nestedData["type"] = billing_meter.CustomerMapping.Type
			if len(nestedData) > 0 {
				if err := d.Set("customer_mapping", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if billing_meter.DefaultAggregation != nil {
		nestedData := make(map[string]interface{})
		nestedData["formula"] = billing_meter.DefaultAggregation.Formula
		if len(nestedData) > 0 {
			if err := d.Set("default_aggregation", []interface{}{nestedData}); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	if _, ok := d.GetOk("value_settings"); ok {
		if billing_meter.ValueSettings != nil {
			nestedData := make(map[string]interface{})
			nestedData["event_payload_key"] = billing_meter.ValueSettings.EventPayloadKey
			if len(nestedData) > 0 {
				if err := d.Set("value_settings", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	return diags
}

func resourceBillingMeterUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_billing_meter resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.BillingMeterUpdateParams{}

	if d.HasChange("display_name") {
		if v, ok := d.Get("display_name").(string); ok && v != "" {
			params.DisplayName = stripe.String(v)
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceBillingMeterRead(ctx, d, meta)
	}

	_, err := c.V1BillingMeters.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update billing_meter: %w", err))
	}

	return resourceBillingMeterRead(ctx, d, meta)
}

func resourceBillingMeterDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Info(ctx, "Marking stripe_billing_meter as inactive instead of deleting", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.BillingMeterDeactivateParams{}

	_, err := c.V1BillingMeters.Deactivate(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to mark billing_meter as inactive: %w", err))
	}

	tflog.Info(ctx, "stripe_billing_meter marked as inactive successfully", map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
