// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2BillingMeteredItem returns the schema for the stripe_v2_billing_metered_item resource
func ResourceV2BillingMeteredItem() *schema.Resource {
	return &schema.Resource{
		Description: "A Metered Item represents a billable item whose pricing is based on usage, measured by a meter. You can use rate cards to specify the pricing and create subscriptions to these items.",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"display_name": {
				Type:        schema.TypeString,
				Description: "Description that customers will see in the invoice line item. Maximum length of 250 characters.",
				Required:    true,
			},
			"invoice_presentation_dimensions": {
				Type:        schema.TypeList,
				Description: "Optional array of Meter dimensions to group event dimension keys for invoice line items.",
				Optional:    true,
				ForceNew:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"lookup_key": {
				Type:        schema.TypeString,
				Description: "An internal key you can use to search for a particular billable item. Must be unique among billable items. Maximum length of 200 characters.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"meter": {
				Type:        schema.TypeString,
				Description: "ID of the Meter that measures usage for this Metered Item.",
				Required:    true,
				ForceNew:    true,
			},
			"unit_label": {
				Type:        schema.TypeString,
				Description: "The unit to use when displaying prices for this billable item in places like Checkout. For example, set this field to \\\"CPU-hour\\\" for Checkout to display \\\"(price) per CPU-hour\\\", or \\\"1 million events\\\" to display \\\"(price) per 1 million events\\\". Maximum length of 100 characters.",
				Optional:    true,
				Computed:    true,
			},
			"meter_segment_conditions": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Optional array of Meter segments to filter event dimension keys for billing.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"dimension": {
							Type:        schema.TypeString,
							Description: "A Meter dimension.",
							Required:    true,
						},
						"value": {
							Type:        schema.TypeString,
							Description: "To count usage towards this metered item, the dimension must have this value.",
							Required:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceV2BillingMeteredItemCreate,
		ReadContext:   resourceV2BillingMeteredItemRead,
		UpdateContext: resourceV2BillingMeteredItemUpdate,
		DeleteContext: resourceV2BillingMeteredItemDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2BillingMeteredItemCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_billing_metered_item resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingMeteredItemCreateParams{}

	if v, ok := d.Get("display_name").(string); ok && v != "" {
		params.DisplayName = stripe.String(v)
	}
	if v, ok := d.Get("invoice_presentation_dimensions").([]interface{}); ok && len(v) > 0 {
		strArr := make([]*string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				strArr[i] = stripe.String(s)
			}
		}
		params.InvoicePresentationDimensions = strArr
	}
	if v, ok := d.Get("lookup_key").(string); ok && v != "" {
		params.LookupKey = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("meter").(string); ok && v != "" {
		params.Meter = stripe.String(v)
	}
	if v, ok := d.Get("unit_label").(string); ok && v != "" {
		params.UnitLabel = stripe.String(v)
	}
	if v, ok := d.Get("meter_segment_conditions").([]interface{}); ok && len(v) > 0 {
		conditions := make([]*stripe.V2BillingMeteredItemCreateMeterSegmentConditionParams, len(v))
		for i, item := range v {
			data := item.(map[string]interface{})
			condition := &stripe.V2BillingMeteredItemCreateMeterSegmentConditionParams{}
			if dimension, ok := data["dimension"].(string); ok && dimension != "" {
				condition.Dimension = stripe.String(dimension)
			}
			if value, ok := data["value"].(string); ok && value != "" {
				condition.Value = stripe.String(value)
			}
			conditions[i] = condition
		}
		params.MeterSegmentConditions = conditions
	}
	v2_billing_metered_item, err := c.V2BillingMeteredItems.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_billing_metered_item: %w", err))
	}

	d.SetId(v2_billing_metered_item.ID)
	return resourceV2BillingMeteredItemRead(ctx, d, meta)
}

func resourceV2BillingMeteredItemRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_billing_metered_item resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	v2_billing_metered_item, err := c.V2BillingMeteredItems.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_billing_metered_item: %w", err))
	}

	if err := d.Set("display_name", v2_billing_metered_item.DisplayName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if v2_billing_metered_item.InvoicePresentationDimensions != nil && len(v2_billing_metered_item.InvoicePresentationDimensions) > 0 {
		if err := d.Set("invoice_presentation_dimensions", v2_billing_metered_item.InvoicePresentationDimensions); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("lookup_key", v2_billing_metered_item.LookupKey); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", v2_billing_metered_item.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("meter", v2_billing_metered_item.Meter); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("unit_label", v2_billing_metered_item.UnitLabel); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if _, ok := d.GetOk("meter_segment_conditions"); ok {
		if v2_billing_metered_item.MeterSegmentConditions != nil && len(v2_billing_metered_item.MeterSegmentConditions) > 0 {
			itemsData := make([]interface{}, len(v2_billing_metered_item.MeterSegmentConditions))
			for i, item := range v2_billing_metered_item.MeterSegmentConditions {
				itemData := make(map[string]interface{})
				if item.Dimension != "" {
					itemData["dimension"] = item.Dimension
				}
				if item.Value != "" {
					itemData["value"] = item.Value
				}
				itemsData[i] = itemData
			}
			if err := d.Set("meter_segment_conditions", itemsData); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	return diags
}

func resourceV2BillingMeteredItemUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_v2_billing_metered_item resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingMeteredItemUpdateParams{}

	if d.HasChange("display_name") {
		if v, ok := d.Get("display_name").(string); ok && v != "" {
			params.DisplayName = stripe.String(v)
		}
	}
	if d.HasChange("lookup_key") {
		if v, ok := d.Get("lookup_key").(string); ok && v != "" {
			params.LookupKey = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions (V2 uses *string)
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]*string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = stripe.String(v.(string))
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = stripe.String("")
			}
		}
	}
	if d.HasChange("unit_label") {
		if v, ok := d.Get("unit_label").(string); ok && v != "" {
			params.UnitLabel = stripe.String(v)
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceV2BillingMeteredItemRead(ctx, d, meta)
	}

	_, err := c.V2BillingMeteredItems.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update v2_billing_metered_item: %w", err))
	}

	return resourceV2BillingMeteredItemRead(ctx, d, meta)
}

func resourceV2BillingMeteredItemDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Warn(ctx, "stripe_v2_billing_metered_item resources cannot be deleted via the Stripe API. "+
		"The resource will be removed from Terraform state but will remain in your Stripe account. "+
		"You may need to archive or deactivate it manually.",
		map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
