// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2BillingPricingPlanComponent returns the schema for the stripe_v2_billing_pricing_plan_component resource
func ResourceV2BillingPricingPlanComponent() *schema.Resource {
	return &schema.Resource{
		Description: "Manages a stripe_v2_billing_pricing_plan_component resource in Stripe.",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"pricing_plan_id": {
				Type:        schema.TypeString,
				Description: "Path parameter: pricing_plan_id",
				Required:    true,
				ForceNew:    true,
			},
			"lookup_key": {
				Type:        schema.TypeString,
				Description: "An identifier that can be used to find this component.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"type": {
				Type:        schema.TypeString,
				Description: "The type of the PricingPlanComponent.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"license_fee",
					"rate_card",
					"service_action",
				}, false)),
			},
			"license_fee": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "Details if this component is a License Fee.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Description: "The ID of the License Fee.",
							Required:    true,
							ForceNew:    true,
						},
						"version": {
							Type:        schema.TypeString,
							Description: "The ID of the License Fee Version. Defaults to 'latest', if not specified.",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
					},
				},
			},
			"rate_card": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "Details if this component is a Rate Card.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Description: "The ID of the Rate Card.",
							Required:    true,
							ForceNew:    true,
						},
						"version": {
							Type:        schema.TypeString,
							Description: "The ID of the Rate Card Version. Defaults to 'latest', if not specified.",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
					},
				},
			},
			"service_action": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "Details if this component is a Service Action.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"id": {
							Type:        schema.TypeString,
							Description: "The ID of the service action.",
							Required:    true,
							ForceNew:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceV2BillingPricingPlanComponentCreate,
		ReadContext:   resourceV2BillingPricingPlanComponentRead,
		UpdateContext: resourceV2BillingPricingPlanComponentUpdate,
		DeleteContext: resourceV2BillingPricingPlanComponentDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2BillingPricingPlanComponentCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_billing_pricing_plan_component resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingPricingPlansComponentCreateParams{}

	if v, ok := d.Get("pricing_plan_id").(string); ok && v != "" {
		params.PricingPlanID = stripe.String(v)
	}

	if v, ok := d.Get("lookup_key").(string); ok && v != "" {
		params.LookupKey = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("type").(string); ok && v != "" {
		params.Type = stripe.String(v)
	}
	if v, ok := d.Get("license_fee").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.LicenseFee = &stripe.V2BillingPricingPlansComponentCreateLicenseFeeParams{}
		if val, ok := data["id"].(string); ok && val != "" {
			params.LicenseFee.ID = stripe.String(val)
		}
		if val, ok := data["version"].(string); ok && val != "" {
			params.LicenseFee.Version = stripe.String(val)
		}
	}
	if v, ok := d.Get("rate_card").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.RateCard = &stripe.V2BillingPricingPlansComponentCreateRateCardParams{}
		if val, ok := data["id"].(string); ok && val != "" {
			params.RateCard.ID = stripe.String(val)
		}
		if val, ok := data["version"].(string); ok && val != "" {
			params.RateCard.Version = stripe.String(val)
		}
	}
	if v, ok := d.Get("service_action").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.ServiceAction = &stripe.V2BillingPricingPlansComponentCreateServiceActionParams{}
		if val, ok := data["id"].(string); ok && val != "" {
			params.ServiceAction.ID = stripe.String(val)
		}
	}
	v2_billing_pricing_plan_component, err := c.V2BillingPricingPlansComponents.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_billing_pricing_plan_component: %w", err))
	}

	d.SetId(v2_billing_pricing_plan_component.ID)
	return resourceV2BillingPricingPlanComponentRead(ctx, d, meta)
}

func resourceV2BillingPricingPlanComponentRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_billing_pricing_plan_component resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingPricingPlansComponentRetrieveParams{}
	if v, ok := d.Get("pricing_plan_id").(string); ok && v != "" {
		params.PricingPlanID = stripe.String(v)
	}

	v2_billing_pricing_plan_component, err := c.V2BillingPricingPlansComponents.Retrieve(ctx, d.Id(), params)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_billing_pricing_plan_component: %w", err))
	}

	if err := d.Set("lookup_key", v2_billing_pricing_plan_component.LookupKey); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", v2_billing_pricing_plan_component.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("type", v2_billing_pricing_plan_component.Type); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if _, ok := d.GetOk("license_fee"); ok {
		if v2_billing_pricing_plan_component.LicenseFee != nil {
			nestedData := make(map[string]interface{})
			nestedData["version"] = v2_billing_pricing_plan_component.LicenseFee.Version
			if len(nestedData) > 0 {
				if err := d.Set("license_fee", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if _, ok := d.GetOk("rate_card"); ok {
		if v2_billing_pricing_plan_component.RateCard != nil {
			nestedData := make(map[string]interface{})
			nestedData["version"] = v2_billing_pricing_plan_component.RateCard.Version
			if len(nestedData) > 0 {
				if err := d.Set("rate_card", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if _, ok := d.GetOk("service_action"); ok {
		if v2_billing_pricing_plan_component.ServiceAction != nil {
			nestedData := make(map[string]interface{})
			if len(nestedData) > 0 {
				if err := d.Set("service_action", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	return diags
}

func resourceV2BillingPricingPlanComponentUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_v2_billing_pricing_plan_component resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingPricingPlansComponentUpdateParams{}

	if v, ok := d.Get("pricing_plan_id").(string); ok && v != "" {
		params.PricingPlanID = stripe.String(v)
	}

	if d.HasChange("lookup_key") {
		if v, ok := d.Get("lookup_key").(string); ok && v != "" {
			params.LookupKey = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions (V2 uses *string)
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]*string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = stripe.String(v.(string))
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = stripe.String("")
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceV2BillingPricingPlanComponentRead(ctx, d, meta)
	}

	_, err := c.V2BillingPricingPlansComponents.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update v2_billing_pricing_plan_component: %w", err))
	}

	return resourceV2BillingPricingPlanComponentRead(ctx, d, meta)
}

func resourceV2BillingPricingPlanComponentDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Deleting stripe_v2_billing_pricing_plan_component resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingPricingPlansComponentDeleteParams{}
	if v, ok := d.Get("pricing_plan_id").(string); ok && v != "" {
		params.PricingPlanID = stripe.String(v)
	}

	_, err := c.V2BillingPricingPlansComponents.Delete(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to delete v2_billing_pricing_plan_component: %w", err))
	}

	d.SetId("")
	return nil
}
