// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"
	"strconv"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourcePrice returns the schema for the stripe_price resource
func ResourcePrice() *schema.Resource {
	return &schema.Resource{
		Description: "Prices define the unit cost, currency, and (optional) billing cycle for both recurring and one-time purchases of products. [Products](https://stripe.com/docs/api#products) help you track inventory or provisioning, and prices help you track payment terms. Different physical goods or levels of service should be represented by products, and pricing options should be represented by prices. This approach lets you change prices without having to change your provisioning scheme. For example, you might have a single \\\"gold\\\" product that has prices for $10/month, $100/year, and €9 once. Related guides: [Set up a subscription](https://stripe.com/docs/billing/subscriptions/set-up-subscription), [create an invoice](https://stripe.com/docs/billing/invoices/create), and more about [products and prices](https://stripe.com/docs/products-prices/overview).",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"active": {
				Type:        schema.TypeBool,
				Description: "Whether the price can be used for new purchases. Defaults to `true`.",
				Optional:    true,
				Default:     true,
			},
			"billing_scheme": {
				Type:        schema.TypeString,
				Description: "Describes how to compute the price per period. Either `per_unit` or `tiered`. `per_unit` indicates that the fixed amount (specified in `unit_amount` or `unit_amount_decimal`) will be charged per unit in `quantity` (for prices with `usage_type=licensed`), or per unit of total usage (for prices with `usage_type=metered`). `tiered` indicates that the unit pricing will be computed using a tiering strategy as defined using the `tiers` and `tiers_mode` attributes.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"per_unit",
					"tiered",
				}, false)),
			},
			"currency": {
				Type:        schema.TypeString,
				Description: "Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).",
				Required:    true,
				ForceNew:    true,
			},
			"currency_options": {
				Type:        schema.TypeList,
				Description: "Prices defined in each available currency option. Each key must be a three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html) and a [supported currency](https://stripe.com/docs/currencies).",
				Optional:    true,
				Computed:    true,
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"key": {
							Type:     schema.TypeString,
							Required: true,
						},
						"custom_unit_amount": {
							Type:        schema.TypeList,
							MaxItems:    1,
							Optional:    true,
							Description: "When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.",
							Elem: &schema.Resource{
								Schema: map[string]*schema.Schema{
									"enabled": {
										Type:        schema.TypeBool,
										Description: "Pass in `true` to enable `custom_unit_amount`, otherwise omit `custom_unit_amount`.",
										Required:    true,
									},
									"maximum": {
										Type:        schema.TypeInt,
										Description: "The maximum unit amount the customer can specify for this item.",
										Optional:    true,
									},
									"minimum": {
										Type:        schema.TypeInt,
										Description: "The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.",
										Optional:    true,
									},
									"preset": {
										Type:        schema.TypeInt,
										Description: "The starting unit amount which can be updated by the customer.",
										Optional:    true,
									},
								},
							},
						},
						"tax_behavior": {
							Type:        schema.TypeString,
							Description: "Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.",
							Optional:    true,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
								"exclusive",
								"inclusive",
								"unspecified",
							}, false)),
						},
						"tiers": {
							Type:        schema.TypeList,
							Description: "Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.",
							Optional:    true,
							Elem:        &schema.Schema{Type: schema.TypeList},
						},
						"unit_amount": {
							Type:        schema.TypeInt,
							Description: "A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge.",
							Optional:    true,
						},
					},
				},
			},
			"lookup_key": {
				Type:        schema.TypeString,
				Description: "A lookup key used to retrieve prices dynamically from a static string. This may be up to 200 characters.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"nickname": {
				Type:        schema.TypeString,
				Description: "A brief description of the price, hidden from customers.",
				Optional:    true,
				Computed:    true,
			},
			"product": {
				Type:        schema.TypeString,
				Description: "The ID of the [Product](https://docs.stripe.com/api/products) that this [Price](https://docs.stripe.com/api/prices) will belong to.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
			},
			"tax_behavior": {
				Type:        schema.TypeString,
				Description: "Only required if a [default tax behavior](https://stripe.com/docs/tax/products-prices-tax-categories-tax-behavior#setting-a-default-tax-behavior-(recommended)) was not provided in the Stripe Tax settings. Specifies whether the price is considered inclusive of taxes or exclusive of taxes. One of `inclusive`, `exclusive`, or `unspecified`. Once specified as either `inclusive` or `exclusive`, it cannot be changed.",
				Optional:    true,
				Computed:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"exclusive",
					"inclusive",
					"unspecified",
				}, false)),
			},
			"tiers_mode": {
				Type:        schema.TypeString,
				Description: "Defines if the tiering price should be `graduated` or `volume` based. In `volume`-based tiering, the maximum quantity within a period determines the per unit price, in `graduated` tiering pricing can successively change as the quantity grows.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"graduated",
					"volume",
				}, false)),
			},
			"unit_amount": {
				Type:        schema.TypeInt,
				Description: "A positive integer in cents (or local equivalent) (or 0 for a free price) representing how much to charge. One of `unit_amount`, `unit_amount_decimal`, or `custom_unit_amount` is required, unless `billing_scheme=tiered`.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
			},
			"custom_unit_amount": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "When set, provides configuration for the amount to be adjusted by the customer during Checkout Sessions and Payment Links.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"maximum": {
							Type:        schema.TypeInt,
							Description: "The maximum unit amount the customer can specify for this item.",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
						"minimum": {
							Type:        schema.TypeInt,
							Description: "The minimum unit amount the customer can specify for this item. Must be at least the minimum charge amount.",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
						"preset": {
							Type:        schema.TypeInt,
							Description: "The starting unit amount which can be updated by the customer.",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
					},
				},
			},
			"recurring": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				ForceNew:    true,
				Description: "The recurring components of a price such as `interval` and `usage_type`.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"interval": {
							Type:        schema.TypeString,
							Description: "Specifies billing frequency. Either `day`, `week`, `month` or `year`.",
							Required:    true,
							ForceNew:    true,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
								"day",
								"month",
								"week",
								"year",
							}, false)),
						},
						"interval_count": {
							Type:        schema.TypeInt,
							Description: "The number of intervals between subscription billings. For example, `interval=month` and `interval_count=3` bills every 3 months. Maximum of three years interval allowed (3 years, 36 months, or 156 weeks).",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
						"meter": {
							Type:        schema.TypeString,
							Description: "The meter tracking the usage of a metered price",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
						"trial_period_days": {
							Type:        schema.TypeInt,
							Description: "Default number of trial days when subscribing a customer to this price using [`trial_from_plan=true`](https://stripe.com/docs/api#create_subscription-trial_from_plan).",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
						},
						"usage_type": {
							Type:        schema.TypeString,
							Description: "Configures how the quantity per period should be determined. Can be either `metered` or `licensed`. `licensed` automatically bills the `quantity` set when adding it to a subscription. `metered` aggregates the total usage based on usage records. Defaults to `licensed`.",
							Optional:    true,
							Computed:    true,
							ForceNew:    true,
							ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
								"licensed",
								"metered",
							}, false)),
						},
					},
				},
			},
			"tiers": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Each element represents a pricing tier. This parameter requires `billing_scheme` to be set to `tiered`. See also the documentation for `billing_scheme`.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"flat_amount": {
							Type:        schema.TypeInt,
							Description: "The flat billing amount for an entire tier, regardless of the number of units in the tier.",
							Optional:    true,
						},
						"flat_amount_decimal": {
							Type:             schema.TypeString,
							Description:      "Same as `flat_amount`, but accepts a decimal value representing an integer in the minor units of the currency. Only one of `flat_amount` and `flat_amount_decimal` can be set.",
							Optional:         true,
							DiffSuppressFunc: suppressDecimalDiff,
						},
						"unit_amount": {
							Type:        schema.TypeInt,
							Description: "The per unit billing amount for each individual unit for which this tier applies.",
							Optional:    true,
						},
						"up_to": {
							Type:     schema.TypeString,
							Required: true,
						},
					},
				},
			},
		},

		CreateContext: resourcePriceCreate,
		ReadContext:   resourcePriceRead,
		UpdateContext: resourcePriceUpdate,
		DeleteContext: resourcePriceDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourcePriceCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_price resource")
	c := meta.(*stripe.Client)

	params := &stripe.PriceCreateParams{}

	params.Active = stripe.Bool(d.Get("active").(bool))
	if v, ok := d.Get("billing_scheme").(string); ok && v != "" {
		params.BillingScheme = stripe.String(v)
	}
	if v, ok := d.Get("currency").(string); ok && v != "" {
		params.Currency = stripe.String(v)
	}
	if v, ok := d.Get("lookup_key").(string); ok && v != "" {
		params.LookupKey = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("nickname").(string); ok && v != "" {
		params.Nickname = stripe.String(v)
	}
	if v, ok := d.Get("product").(string); ok && v != "" {
		params.Product = stripe.String(v)
	}
	if v, ok := d.Get("tax_behavior").(string); ok && v != "" {
		params.TaxBehavior = stripe.String(v)
	}
	if v, ok := d.Get("tiers_mode").(string); ok && v != "" {
		params.TiersMode = stripe.String(v)
	}
	if !d.GetRawConfig().GetAttr("unit_amount").IsNull() {
		params.UnitAmount = stripe.Int64(int64(d.Get("unit_amount").(int)))
	}
	if v, ok := d.Get("custom_unit_amount").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.CustomUnitAmount = &stripe.PriceCreateCustomUnitAmountParams{}
		if val, ok := data["maximum"].(int); ok && val > 0 {
			params.CustomUnitAmount.Maximum = stripe.Int64(int64(val))
		}
		if val, ok := data["minimum"].(int); ok && val > 0 {
			params.CustomUnitAmount.Minimum = stripe.Int64(int64(val))
		}
		if val, ok := data["preset"].(int); ok && val > 0 {
			params.CustomUnitAmount.Preset = stripe.Int64(int64(val))
		}
		params.CustomUnitAmount.Enabled = stripe.Bool(true)
	}
	if v, ok := d.Get("recurring").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.Recurring = &stripe.PriceCreateRecurringParams{}
		if val, ok := data["interval"].(string); ok && val != "" {
			params.Recurring.Interval = stripe.String(val)
		}
		if val, ok := data["interval_count"].(int); ok && val > 0 {
			params.Recurring.IntervalCount = stripe.Int64(int64(val))
		}
		if val, ok := data["meter"].(string); ok && val != "" {
			params.Recurring.Meter = stripe.String(val)
		}
		if val, ok := data["trial_period_days"].(int); ok && val > 0 {
			params.Recurring.TrialPeriodDays = stripe.Int64(int64(val))
		}
		if val, ok := data["usage_type"].(string); ok && val != "" {
			params.Recurring.UsageType = stripe.String(val)
		}
	}
	if v, ok := d.Get("currency_options").([]interface{}); ok && len(v) > 0 {
		params.CurrencyOptions = make(map[string]*stripe.PriceCreateCurrencyOptionsParams)
		for _, raw := range v {
			if item, ok := raw.(map[string]interface{}); ok {
				key, _ := item["key"].(string)
				if key == "" {
					continue
				}
				entry := &stripe.PriceCreateCurrencyOptionsParams{}
				if val, ok := item["tax_behavior"].(string); ok && val != "" {
					entry.TaxBehavior = stripe.String(val)
				}
				if val, ok := item["unit_amount"].(int); ok {
					entry.UnitAmount = stripe.Int64(int64(val))
				}
				params.CurrencyOptions[key] = entry
			}
		}
	}
	if v, ok := d.Get("tiers").([]interface{}); ok && len(v) > 0 {
		conditions := make([]*stripe.PriceCreateTierParams, len(v))
		for i, item := range v {
			data := item.(map[string]interface{})
			condition := &stripe.PriceCreateTierParams{}
			if val, ok := data["flat_amount"].(int); ok {
				condition.FlatAmount = stripe.Int64(int64(val))
			}
			if flat_amount_decimal, ok := data["flat_amount_decimal"].(string); ok && flat_amount_decimal != "" {
				if f, err := strconv.ParseFloat(flat_amount_decimal, 64); err == nil {
					condition.FlatAmountDecimal = stripe.Float64(f)
				}
			}
			if val, ok := data["unit_amount"].(int); ok {
				condition.UnitAmount = stripe.Int64(int64(val))
			}
			if up_to, ok := data["up_to"].(string); ok && up_to != "" {
				if up_to == "inf" {
					condition.UpToInf = stripe.Bool(true)
				} else if i, err := strconv.ParseInt(up_to, 10, 64); err == nil {
					condition.UpTo = stripe.Int64(i)
				}
			}
			conditions[i] = condition
		}
		params.Tiers = conditions
	}
	price, err := c.V1Prices.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create price: %w", err))
	}

	d.SetId(price.ID)
	return resourcePriceRead(ctx, d, meta)
}

func resourcePriceRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_price resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	price, err := c.V1Prices.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read price: %w", err))
	}

	if err := d.Set("active", price.Active); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("billing_scheme", price.BillingScheme); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("currency", price.Currency); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if price.CurrencyOptions != nil && len(price.CurrencyOptions) > 0 {
		itemsData := make([]interface{}, 0, len(price.CurrencyOptions))
		for k, item := range price.CurrencyOptions {
			if item == nil {
				continue
			}
			itemData := make(map[string]interface{})
			itemData["key"] = k
			if item.TaxBehavior != "" {
				itemData["tax_behavior"] = item.TaxBehavior
			}
			itemData["unit_amount"] = int(item.UnitAmount)
			if item.UnitAmountDecimal != 0 {
				itemData["unit_amount_decimal"] = normalizeDecimalFloat(item.UnitAmountDecimal)
			}
			if len(itemData) > 0 {
				itemsData = append(itemsData, itemData)
			}
		}
		if err := d.Set("currency_options", itemsData); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("lookup_key", price.LookupKey); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", price.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("nickname", price.Nickname); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tax_behavior", price.TaxBehavior); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tiers_mode", price.TiersMode); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("unit_amount", price.UnitAmount); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if price.Product != nil {
		if err := d.Set("product", price.Product.ID); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if _, ok := d.GetOk("custom_unit_amount"); ok {
		if price.CustomUnitAmount != nil {
			nestedData := make(map[string]interface{})
			nestedData["maximum"] = int(price.CustomUnitAmount.Maximum)
			nestedData["minimum"] = int(price.CustomUnitAmount.Minimum)
			nestedData["preset"] = int(price.CustomUnitAmount.Preset)
			if len(nestedData) > 0 {
				if err := d.Set("custom_unit_amount", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if _, ok := d.GetOk("recurring"); ok {
		if price.Recurring != nil {
			nestedData := make(map[string]interface{})
			nestedData["interval"] = price.Recurring.Interval
			nestedData["interval_count"] = int(price.Recurring.IntervalCount)
			nestedData["meter"] = price.Recurring.Meter
			nestedData["trial_period_days"] = int(price.Recurring.TrialPeriodDays)
			nestedData["usage_type"] = price.Recurring.UsageType
			if len(nestedData) > 0 {
				if err := d.Set("recurring", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if _, ok := d.GetOk("tiers"); ok {
		if price.Tiers != nil && len(price.Tiers) > 0 {
			itemsData := make([]interface{}, len(price.Tiers))
			for i, item := range price.Tiers {
				itemData := make(map[string]interface{})
				itemData["flat_amount"] = int(item.FlatAmount)
				if item.FlatAmountDecimal != 0 {
					itemData["flat_amount_decimal"] = normalizeDecimalFloat(item.FlatAmountDecimal)
				}
				itemData["unit_amount"] = int(item.UnitAmount)
				if item.UnitAmountDecimal != 0 {
					itemData["unit_amount_decimal"] = normalizeDecimalFloat(item.UnitAmountDecimal)
				}
				itemData["up_to"] = strconv.FormatInt(item.UpTo, 10)
				itemsData[i] = itemData
			}
			if err := d.Set("tiers", itemsData); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	return diags
}

func resourcePriceUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_price resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.PriceUpdateParams{}

	if d.HasChange("active") {
		params.Active = stripe.Bool(d.Get("active").(bool))
	}
	if d.HasChange("lookup_key") {
		if v, ok := d.Get("lookup_key").(string); ok && v != "" {
			params.LookupKey = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = v.(string)
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = ""
			}
		}
	}
	if d.HasChange("nickname") {
		if v, ok := d.Get("nickname").(string); ok && v != "" {
			params.Nickname = stripe.String(v)
		}
	}
	if d.HasChange("tax_behavior") {
		if v, ok := d.Get("tax_behavior").(string); ok && v != "" {
			params.TaxBehavior = stripe.String(v)
		}
	}
	if d.HasChange("currency_options") {
		if v, ok := d.Get("currency_options").([]interface{}); ok && len(v) > 0 {
			params.CurrencyOptions = make(map[string]*stripe.PriceUpdateCurrencyOptionsParams)
			for _, raw := range v {
				if item, ok := raw.(map[string]interface{}); ok {
					key, _ := item["key"].(string)
					if key == "" {
						continue
					}
					entry := &stripe.PriceUpdateCurrencyOptionsParams{}
					if val, ok := item["tax_behavior"].(string); ok && val != "" {
						entry.TaxBehavior = stripe.String(val)
					}
					if val, ok := item["unit_amount"].(int); ok {
						entry.UnitAmount = stripe.Int64(int64(val))
					}
					params.CurrencyOptions[key] = entry
				}
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourcePriceRead(ctx, d, meta)
	}

	_, err := c.V1Prices.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update price: %w", err))
	}

	return resourcePriceRead(ctx, d, meta)
}

func resourcePriceDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Info(ctx, "Marking stripe_price as inactive instead of deleting", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.PriceUpdateParams{
		Active: stripe.Bool(false),
	}

	_, err := c.V1Prices.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to mark price as inactive: %w", err))
	}

	tflog.Info(ctx, "stripe_price marked as inactive successfully", map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
