// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceProduct returns the schema for the stripe_product resource
func ResourceProduct() *schema.Resource {
	return &schema.Resource{
		Description: "Products describe the specific goods or services you offer to your customers. For example, you might offer a Standard and Premium version of your goods or service; each version would be a separate Product. They can be used in conjunction with [Prices](https://stripe.com/docs/api#prices) to configure pricing in Payment Links, Checkout, and Subscriptions. Related guides: [Set up a subscription](https://stripe.com/docs/billing/subscriptions/set-up-subscription), [share a Payment Link](https://stripe.com/docs/payment-links), [accept payments with Checkout](https://stripe.com/docs/payments/accept-a-payment#create-product-prices-upfront), and more about [Products and Prices](https://stripe.com/docs/products-prices/overview)",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"active": {
				Type:        schema.TypeBool,
				Description: "Whether the product is currently available for purchase. Defaults to `true`.",
				Optional:    true,
				Default:     true,
			},
			"description": {
				Type:        schema.TypeString,
				Description: "The product's description, meant to be displayable to the customer. Use this field to optionally store a long form explanation of the product being sold for your own rendering purposes.",
				Optional:    true,
				Computed:    true,
			},
			"images": {
				Type:        schema.TypeList,
				Description: "A list of up to 8 URLs of images for this product, meant to be displayable to the customer.",
				Optional:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](https://stripe.com/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format. Individual keys can be unset by posting an empty value to them. All keys can be unset by posting an empty value to `metadata`.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"name": {
				Type:        schema.TypeString,
				Description: "The product's name, meant to be displayable to the customer.",
				Required:    true,
			},
			"shippable": {
				Type:        schema.TypeBool,
				Description: "Whether this product is shipped (i.e., physical goods).",
				Optional:    true,
				Computed:    true,
			},
			"statement_descriptor": {
				Type:        schema.TypeString,
				Description: "An arbitrary string to be displayed on your customer's credit card or bank statement. While most banks display this information consistently, some may display it incorrectly or not at all. This may be up to 22 characters. The statement description may not include `<`, `>`, `\\`, `\\\"`, `'` characters, and will appear on your customer's statement in capital letters. Non-ASCII characters are automatically stripped. It must contain at least one letter. Only used for subscription payments.",
				Optional:    true,
				Computed:    true,
			},
			"tax_code": {
				Type:        schema.TypeString,
				Description: "A [tax code](https://stripe.com/docs/tax/tax-categories) ID.",
				Optional:    true,
				Computed:    true,
			},
			"type": {
				Type:        schema.TypeString,
				Description: "The type of the product. Defaults to `service` if not explicitly specified, enabling use of this product with Subscriptions and Plans. Set this parameter to `good` to use this product with Orders and SKUs. On API versions before `2018-02-05`, this field defaults to `good` for compatibility reasons.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"good",
					"service",
				}, false)),
			},
			"unit_label": {
				Type:        schema.TypeString,
				Description: "A label that represents units of this product. When set, this will be included in customers' receipts, invoices, Checkout, and the customer portal.",
				Optional:    true,
				Computed:    true,
			},
			"url": {
				Type:        schema.TypeString,
				Description: "A URL of a publicly-accessible webpage for this product.",
				Optional:    true,
				Computed:    true,
			},
			"package_dimensions": {
				Type:        schema.TypeList,
				MaxItems:    1,
				Optional:    true,
				Description: "The dimensions of this product for shipping purposes.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"height": {
							Type:        schema.TypeFloat,
							Description: "Height, in inches. Maximum precision is 2 decimal places.",
							Required:    true,
						},
						"length": {
							Type:        schema.TypeFloat,
							Description: "Length, in inches. Maximum precision is 2 decimal places.",
							Required:    true,
						},
						"weight": {
							Type:        schema.TypeFloat,
							Description: "Weight, in ounces. Maximum precision is 2 decimal places.",
							Required:    true,
						},
						"width": {
							Type:        schema.TypeFloat,
							Description: "Width, in inches. Maximum precision is 2 decimal places.",
							Required:    true,
						},
					},
				},
			},
			"marketing_features": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "A list of up to 15 marketing features for this product. These are displayed in [pricing tables](https://stripe.com/docs/payments/checkout/pricing-table).",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"name": {
							Type:        schema.TypeString,
							Description: "The marketing feature name. Up to 80 characters long.",
							Required:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceProductCreate,
		ReadContext:   resourceProductRead,
		UpdateContext: resourceProductUpdate,
		DeleteContext: resourceProductDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceProductCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_product resource")
	c := meta.(*stripe.Client)

	params := &stripe.ProductCreateParams{}

	params.Active = stripe.Bool(d.Get("active").(bool))
	if v, ok := d.Get("description").(string); ok && v != "" {
		params.Description = stripe.String(v)
	}
	if v, ok := d.Get("images").([]interface{}); ok && len(v) > 0 {
		strArr := make([]*string, len(v))
		for i, item := range v {
			if s, ok := item.(string); ok {
				strArr[i] = stripe.String(s)
			}
		}
		params.Images = strArr
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("name").(string); ok && v != "" {
		params.Name = stripe.String(v)
	}
	if !d.GetRawConfig().GetAttr("shippable").IsNull() {
		params.Shippable = stripe.Bool(d.Get("shippable").(bool))
	}
	if v, ok := d.Get("statement_descriptor").(string); ok && v != "" {
		params.StatementDescriptor = stripe.String(v)
	}
	if v, ok := d.Get("tax_code").(string); ok && v != "" {
		params.TaxCode = stripe.String(v)
	}
	if v, ok := d.Get("type").(string); ok && v != "" {
		params.Type = stripe.String(v)
	}
	if v, ok := d.Get("unit_label").(string); ok && v != "" {
		params.UnitLabel = stripe.String(v)
	}
	if v, ok := d.Get("url").(string); ok && v != "" {
		params.URL = stripe.String(v)
	}
	if v, ok := d.Get("package_dimensions").([]interface{}); ok && len(v) > 0 {
		data := v[0].(map[string]interface{})
		params.PackageDimensions = &stripe.ProductCreatePackageDimensionsParams{}
		if val, ok := data["height"].(float64); ok {
			params.PackageDimensions.Height = stripe.Float64(val)
		}
		if val, ok := data["length"].(float64); ok {
			params.PackageDimensions.Length = stripe.Float64(val)
		}
		if val, ok := data["weight"].(float64); ok {
			params.PackageDimensions.Weight = stripe.Float64(val)
		}
		if val, ok := data["width"].(float64); ok {
			params.PackageDimensions.Width = stripe.Float64(val)
		}
	}
	if v, ok := d.Get("marketing_features").([]interface{}); ok && len(v) > 0 {
		conditions := make([]*stripe.ProductCreateMarketingFeatureParams, len(v))
		for i, item := range v {
			data := item.(map[string]interface{})
			condition := &stripe.ProductCreateMarketingFeatureParams{}
			if name, ok := data["name"].(string); ok && name != "" {
				condition.Name = stripe.String(name)
			}
			conditions[i] = condition
		}
		params.MarketingFeatures = conditions
	}
	product, err := c.V1Products.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create product: %w", err))
	}

	d.SetId(product.ID)
	return resourceProductRead(ctx, d, meta)
}

func resourceProductRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_product resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	product, err := c.V1Products.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read product: %w", err))
	}

	if err := d.Set("active", product.Active); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("description", product.Description); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if product.Images != nil && len(product.Images) > 0 {
		if err := d.Set("images", product.Images); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if err := d.Set("metadata", product.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("name", product.Name); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("shippable", product.Shippable); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("statement_descriptor", product.StatementDescriptor); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("type", product.Type); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("unit_label", product.UnitLabel); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("url", product.URL); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if product.TaxCode != nil {
		if err := d.Set("tax_code", product.TaxCode.ID); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if _, ok := d.GetOk("package_dimensions"); ok {
		if product.PackageDimensions != nil {
			nestedData := make(map[string]interface{})
			nestedData["height"] = product.PackageDimensions.Height
			nestedData["length"] = product.PackageDimensions.Length
			nestedData["weight"] = product.PackageDimensions.Weight
			nestedData["width"] = product.PackageDimensions.Width
			if len(nestedData) > 0 {
				if err := d.Set("package_dimensions", []interface{}{nestedData}); err != nil {
					diags = append(diags, diag.FromErr(err)...)
				}
			}
		}
	}
	if _, ok := d.GetOk("marketing_features"); ok {
		if product.MarketingFeatures != nil && len(product.MarketingFeatures) > 0 {
			itemsData := make([]interface{}, len(product.MarketingFeatures))
			for i, item := range product.MarketingFeatures {
				itemData := make(map[string]interface{})
				if item.Name != "" {
					itemData["name"] = item.Name
				}
				itemsData[i] = itemData
			}
			if err := d.Set("marketing_features", itemsData); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	return diags
}

func resourceProductUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_product resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.ProductUpdateParams{}

	if d.HasChange("active") {
		params.Active = stripe.Bool(d.Get("active").(bool))
	}
	if d.HasChange("description") {
		if v, ok := d.Get("description").(string); ok && v != "" {
			params.Description = stripe.String(v)
		}
	}
	if d.HasChange("images") {
		if v, ok := d.Get("images").([]interface{}); ok && len(v) > 0 {
			strArr := make([]*string, len(v))
			for i, item := range v {
				if s, ok := item.(string); ok {
					strArr[i] = stripe.String(s)
				}
			}
			params.Images = strArr
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = v.(string)
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = ""
			}
		}
	}
	if d.HasChange("name") {
		if v, ok := d.Get("name").(string); ok && v != "" {
			params.Name = stripe.String(v)
		}
	}
	if d.HasChange("shippable") {
		params.Shippable = stripe.Bool(d.Get("shippable").(bool))
	}
	if d.HasChange("statement_descriptor") {
		if v, ok := d.Get("statement_descriptor").(string); ok && v != "" {
			params.StatementDescriptor = stripe.String(v)
		}
	}
	if d.HasChange("tax_code") {
		if v, ok := d.Get("tax_code").(string); ok && v != "" {
			params.TaxCode = stripe.String(v)
		}
	}
	if d.HasChange("unit_label") {
		if v, ok := d.Get("unit_label").(string); ok && v != "" {
			params.UnitLabel = stripe.String(v)
		}
	}
	if d.HasChange("url") {
		if v, ok := d.Get("url").(string); ok && v != "" {
			params.URL = stripe.String(v)
		}
	}
	if d.HasChange("marketing_features") {
		if v, ok := d.Get("marketing_features").([]interface{}); ok && len(v) > 0 {
			conditions := make([]*stripe.ProductUpdateMarketingFeatureParams, len(v))
			for i, item := range v {
				data := item.(map[string]interface{})
				condition := &stripe.ProductUpdateMarketingFeatureParams{}
				if val, ok := data["name"].(string); ok && val != "" {
					condition.Name = stripe.String(val)
				}
				conditions[i] = condition
			}
			params.MarketingFeatures = conditions
		}
	}
	if d.HasChange("package_dimensions") {
		if v, ok := d.Get("package_dimensions").([]interface{}); ok && len(v) > 0 {
			data := v[0].(map[string]interface{})
			params.PackageDimensions = &stripe.ProductUpdatePackageDimensionsParams{}
			if val, ok := data["height"].(float64); ok {
				params.PackageDimensions.Height = stripe.Float64(val)
			}
			if val, ok := data["length"].(float64); ok {
				params.PackageDimensions.Length = stripe.Float64(val)
			}
			if val, ok := data["weight"].(float64); ok {
				params.PackageDimensions.Weight = stripe.Float64(val)
			}
			if val, ok := data["width"].(float64); ok {
				params.PackageDimensions.Width = stripe.Float64(val)
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceProductRead(ctx, d, meta)
	}

	_, err := c.V1Products.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update product: %w", err))
	}

	return resourceProductRead(ctx, d, meta)
}

func resourceProductDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Info(ctx, "Marking stripe_product as inactive instead of deleting", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.ProductUpdateParams{
		Active: stripe.Bool(false),
	}

	_, err := c.V1Products.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to mark product as inactive: %w", err))
	}

	tflog.Info(ctx, "stripe_product marked as inactive successfully", map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
