// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2BillingLicenseFee returns the schema for the stripe_v2_billing_license_fee resource
func ResourceV2BillingLicenseFee() *schema.Resource {
	return &schema.Resource{
		Description: "Manages a stripe_v2_billing_license_fee resource in Stripe.",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"currency": {
				Type:        schema.TypeString,
				Description: "Three-letter ISO currency code, in lowercase. Must be a supported currency.",
				Required:    true,
				ForceNew:    true,
			},
			"display_name": {
				Type:        schema.TypeString,
				Description: "A customer-facing name for the License Fee. This name is used in Stripe-hosted products like the Customer Portal and Checkout. It does not show up on Invoices. Maximum length of 250 characters.",
				Required:    true,
			},
			"licensed_item": {
				Type:        schema.TypeString,
				Description: "The Licensed Item that this License Fee binds to.",
				Required:    true,
				ForceNew:    true,
			},
			"lookup_key": {
				Type:        schema.TypeString,
				Description: "An internal key you can use to search for a particular license fee. Maximum length of 200 characters.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"service_interval": {
				Type:        schema.TypeString,
				Description: "The interval for assessing service. For example, a monthly license fee with a rate of $1 for the first 10 \\\"workloads\\\" and $2 thereafter means \\\"$1 per workload up to 10 workloads during a month of service.\\\" This is similar to but distinct from billing interval; the service interval deals with the rate at which the customer accumulates fees, while the billing interval in Cadence deals with the rate the customer is billed.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"day",
					"month",
					"week",
					"year",
				}, false)),
			},
			"service_interval_count": {
				Type:        schema.TypeInt,
				Description: "The length of the interval for assessing service. For example, set this to 3 and `service_interval` to `\\\"month\\\"` in order to specify quarterly service.",
				Required:    true,
				ForceNew:    true,
			},
			"tax_behavior": {
				Type:        schema.TypeString,
				Description: "The Stripe Tax tax behavior - whether the license fee is inclusive or exclusive of tax.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"exclusive",
					"inclusive",
				}, false)),
			},
			"tiering_mode": {
				Type:        schema.TypeString,
				Description: "Defines whether the tiered price should be graduated or volume-based. In volume-based tiering, the maximum quantity within a period determines the per-unit price. In graduated tiering, the pricing changes as the quantity grows into new tiers. Can only be set if `tiers` is set.",
				Optional:    true,
				Computed:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"graduated",
					"volume",
				}, false)),
			},
			"unit_amount": {
				Type:        schema.TypeString,
				Description: "The per-unit amount to be charged, represented as a decimal string in minor currency units with at most 12 decimal places. Cannot be set if `tiers` is provided.",
				Optional:    true,
				Computed:    true,
			},
			"tiers": {
				Type:        schema.TypeList,
				Optional:    true,
				Description: "Each element represents a pricing tier. Cannot be set if `unit_amount` is provided.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"flat_amount": {
							Type:        schema.TypeString,
							Description: "Price for the entire tier, represented as a decimal string in minor currency units with at most 12 decimal places.",
							Optional:    true,
						},
						"unit_amount": {
							Type:        schema.TypeString,
							Description: "Per-unit price for units included in this tier, represented as a decimal string in minor currency units with at most 12 decimal places.",
							Optional:    true,
						},
						"up_to_decimal": {
							Type:        schema.TypeString,
							Description: "Up to and including this quantity will be contained in the tier. Only one of `up_to_decimal` and `up_to_inf` may be set.",
							Optional:    true,
						},
						"up_to_inf": {
							Type:        schema.TypeString,
							Description: "No upper bound to this tier. Only one of `up_to_decimal` and `up_to_inf` may be set.",
							Optional:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceV2BillingLicenseFeeCreate,
		ReadContext:   resourceV2BillingLicenseFeeRead,
		UpdateContext: resourceV2BillingLicenseFeeUpdate,
		DeleteContext: resourceV2BillingLicenseFeeDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2BillingLicenseFeeCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_billing_license_fee resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingLicenseFeeCreateParams{}

	if v, ok := d.Get("currency").(string); ok && v != "" {
		params.Currency = stripe.String(v)
	}
	if v, ok := d.Get("display_name").(string); ok && v != "" {
		params.DisplayName = stripe.String(v)
	}
	if v, ok := d.Get("licensed_item").(string); ok && v != "" {
		params.LicensedItem = stripe.String(v)
	}
	if v, ok := d.Get("lookup_key").(string); ok && v != "" {
		params.LookupKey = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("service_interval").(string); ok && v != "" {
		params.ServiceInterval = stripe.String(v)
	}
	params.ServiceIntervalCount = stripe.Int64(int64(d.Get("service_interval_count").(int)))
	if v, ok := d.Get("tax_behavior").(string); ok && v != "" {
		params.TaxBehavior = stripe.String(v)
	}
	if v, ok := d.Get("tiering_mode").(string); ok && v != "" {
		params.TieringMode = stripe.String(v)
	}
	if v, ok := d.Get("unit_amount").(string); ok && v != "" {
		params.UnitAmount = stripe.String(v)
	}
	if v, ok := d.Get("tiers").([]interface{}); ok && len(v) > 0 {
		conditions := make([]*stripe.V2BillingLicenseFeeCreateTierParams, len(v))
		for i, item := range v {
			data := item.(map[string]interface{})
			condition := &stripe.V2BillingLicenseFeeCreateTierParams{}
			if flat_amount, ok := data["flat_amount"].(string); ok && flat_amount != "" {
				condition.FlatAmount = stripe.String(flat_amount)
			}
			if unit_amount, ok := data["unit_amount"].(string); ok && unit_amount != "" {
				condition.UnitAmount = stripe.String(unit_amount)
			}
			if up_to_decimal, ok := data["up_to_decimal"].(string); ok && up_to_decimal != "" {
				condition.UpToDecimal = stripe.String(up_to_decimal)
			}
			if up_to_inf, ok := data["up_to_inf"].(string); ok && up_to_inf != "" {
				condition.UpToInf = stripe.String(up_to_inf)
			}
			conditions[i] = condition
		}
		params.Tiers = conditions
	}
	v2_billing_license_fee, err := c.V2BillingLicenseFees.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_billing_license_fee: %w", err))
	}

	d.SetId(v2_billing_license_fee.ID)
	return resourceV2BillingLicenseFeeRead(ctx, d, meta)
}

func resourceV2BillingLicenseFeeRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_billing_license_fee resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	v2_billing_license_fee, err := c.V2BillingLicenseFees.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_billing_license_fee: %w", err))
	}

	if err := d.Set("currency", v2_billing_license_fee.Currency); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("display_name", v2_billing_license_fee.DisplayName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("lookup_key", v2_billing_license_fee.LookupKey); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", v2_billing_license_fee.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("service_interval", v2_billing_license_fee.ServiceInterval); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("service_interval_count", v2_billing_license_fee.ServiceIntervalCount); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tax_behavior", v2_billing_license_fee.TaxBehavior); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tiering_mode", v2_billing_license_fee.TieringMode); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("unit_amount", normalizeDecimalString(v2_billing_license_fee.UnitAmount)); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if v2_billing_license_fee.LicensedItem != nil {
		if err := d.Set("licensed_item", v2_billing_license_fee.LicensedItem.ID); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if _, ok := d.GetOk("tiers"); ok {
		if v2_billing_license_fee.Tiers != nil && len(v2_billing_license_fee.Tiers) > 0 {
			itemsData := make([]interface{}, len(v2_billing_license_fee.Tiers))
			for i, item := range v2_billing_license_fee.Tiers {
				itemData := make(map[string]interface{})
				if item.FlatAmount != "" {
					itemData["flat_amount"] = item.FlatAmount
				}
				if item.UnitAmount != "" {
					itemData["unit_amount"] = item.UnitAmount
				}
				if item.UpToDecimal != "" {
					itemData["up_to_decimal"] = item.UpToDecimal
				}
				if item.UpToInf != "" {
					itemData["up_to_inf"] = item.UpToInf
				}
				itemsData[i] = itemData
			}
			if err := d.Set("tiers", itemsData); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	return diags
}

func resourceV2BillingLicenseFeeUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_v2_billing_license_fee resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingLicenseFeeUpdateParams{}

	if d.HasChange("tiers") || d.HasChange("tiering_mode") {
		// These fields must be sent together
		if v, ok := d.Get("tiers").([]interface{}); ok && len(v) > 0 {
			conditions := make([]*stripe.V2BillingLicenseFeeUpdateTierParams, len(v))
			for i, item := range v {
				data := item.(map[string]interface{})
				condition := &stripe.V2BillingLicenseFeeUpdateTierParams{}
				if val, ok := data["flat_amount"].(string); ok && val != "" {
					condition.FlatAmount = stripe.String(val)
				}
				if val, ok := data["unit_amount"].(string); ok && val != "" {
					condition.UnitAmount = stripe.String(val)
				}
				if val, ok := data["up_to_decimal"].(string); ok && val != "" {
					condition.UpToDecimal = stripe.String(val)
				}
				if val, ok := data["up_to_inf"].(string); ok && val != "" {
					condition.UpToInf = stripe.String(val)
				}
				conditions[i] = condition
			}
			params.Tiers = conditions
		}
		if v, ok := d.Get("tiering_mode").(string); ok && v != "" {
			params.TieringMode = stripe.String(v)
		}
	}
	if d.HasChange("display_name") {
		if v, ok := d.Get("display_name").(string); ok && v != "" {
			params.DisplayName = stripe.String(v)
		}
	}
	if d.HasChange("lookup_key") {
		if v, ok := d.Get("lookup_key").(string); ok && v != "" {
			params.LookupKey = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions (V2 uses *string)
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]*string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = stripe.String(v.(string))
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = stripe.String("")
			}
		}
	}
	if d.HasChange("unit_amount") {
		if v, ok := d.Get("unit_amount").(string); ok && v != "" {
			params.UnitAmount = stripe.String(v)
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceV2BillingLicenseFeeRead(ctx, d, meta)
	}

	_, err := c.V2BillingLicenseFees.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update v2_billing_license_fee: %w", err))
	}

	return resourceV2BillingLicenseFeeRead(ctx, d, meta)
}

func resourceV2BillingLicenseFeeDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Warn(ctx, "stripe_v2_billing_license_fee resources cannot be deleted via the Stripe API. "+
		"The resource will be removed from Terraform state but will remain in your Stripe account. "+
		"You may need to archive or deactivate it manually.",
		map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
