// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2BillingRateCard returns the schema for the stripe_v2_billing_rate_card resource
func ResourceV2BillingRateCard() *schema.Resource {
	return &schema.Resource{
		Description: "A Rate Card represents a versioned set of usage-based prices (rates). Each rate is associated with one Metered Item and defines how much to charge for usage of that item. After you've set up a RateCard, you can subscribe customers to it by creating a Rate Card Subscription.",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"currency": {
				Type:        schema.TypeString,
				Description: "The currency of this RateCard.",
				Required:    true,
				ForceNew:    true,
			},
			"display_name": {
				Type:        schema.TypeString,
				Description: "A customer-facing name for the RateCard. This name is used in Stripe-hosted products like the Customer Portal and Checkout. It does not show up on Invoices. Maximum length of 250 characters.",
				Required:    true,
			},
			"lookup_key": {
				Type:        schema.TypeString,
				Description: "An internal key you can use to search for a particular RateCard. Maximum length of 200 characters.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"service_interval": {
				Type:        schema.TypeString,
				Description: "The interval for assessing service. For example, a monthly RateCard with a rate of $1 for the first 10 \\\"workloads\\\" and $2 thereafter means \\\"$1 per workload up to 10 workloads during a month of service.\\\" This is similar to but distinct from billing interval; the service interval deals with the rate at which the customer accumulates fees, while the billing interval in Cadence deals with the rate the customer is billed.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"day",
					"month",
					"week",
					"year",
				}, false)),
			},
			"service_interval_count": {
				Type:        schema.TypeInt,
				Description: "The length of the interval for assessing service. For example, set this to 3 and `service_interval` to `\\\"month\\\"` in order to specify quarterly service.",
				Required:    true,
				ForceNew:    true,
			},
			"tax_behavior": {
				Type:        schema.TypeString,
				Description: "The Stripe Tax tax behavior - whether the rates are inclusive or exclusive of tax.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"exclusive",
					"inclusive",
				}, false)),
			},
		},

		CreateContext: resourceV2BillingRateCardCreate,
		ReadContext:   resourceV2BillingRateCardRead,
		UpdateContext: resourceV2BillingRateCardUpdate,
		DeleteContext: resourceV2BillingRateCardDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2BillingRateCardCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_billing_rate_card resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingRateCardCreateParams{}

	if v, ok := d.Get("currency").(string); ok && v != "" {
		params.Currency = stripe.String(v)
	}
	if v, ok := d.Get("display_name").(string); ok && v != "" {
		params.DisplayName = stripe.String(v)
	}
	if v, ok := d.Get("lookup_key").(string); ok && v != "" {
		params.LookupKey = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("service_interval").(string); ok && v != "" {
		params.ServiceInterval = stripe.String(v)
	}
	params.ServiceIntervalCount = stripe.Int64(int64(d.Get("service_interval_count").(int)))
	if v, ok := d.Get("tax_behavior").(string); ok && v != "" {
		params.TaxBehavior = stripe.String(v)
	}
	v2_billing_rate_card, err := c.V2BillingRateCards.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_billing_rate_card: %w", err))
	}

	d.SetId(v2_billing_rate_card.ID)
	return resourceV2BillingRateCardRead(ctx, d, meta)
}

func resourceV2BillingRateCardRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_billing_rate_card resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	v2_billing_rate_card, err := c.V2BillingRateCards.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_billing_rate_card: %w", err))
	}

	if err := d.Set("currency", v2_billing_rate_card.Currency); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("display_name", v2_billing_rate_card.DisplayName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("lookup_key", v2_billing_rate_card.LookupKey); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", v2_billing_rate_card.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("service_interval", v2_billing_rate_card.ServiceInterval); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("service_interval_count", v2_billing_rate_card.ServiceIntervalCount); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tax_behavior", v2_billing_rate_card.TaxBehavior); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	return diags
}

func resourceV2BillingRateCardUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_v2_billing_rate_card resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingRateCardUpdateParams{}

	if d.HasChange("display_name") {
		if v, ok := d.Get("display_name").(string); ok && v != "" {
			params.DisplayName = stripe.String(v)
		}
	}
	if d.HasChange("lookup_key") {
		if v, ok := d.Get("lookup_key").(string); ok && v != "" {
			params.LookupKey = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions (V2 uses *string)
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]*string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = stripe.String(v.(string))
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = stripe.String("")
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceV2BillingRateCardRead(ctx, d, meta)
	}

	_, err := c.V2BillingRateCards.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update v2_billing_rate_card: %w", err))
	}

	return resourceV2BillingRateCardRead(ctx, d, meta)
}

func resourceV2BillingRateCardDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Warn(ctx, "stripe_v2_billing_rate_card resources cannot be deleted via the Stripe API. "+
		"The resource will be removed from Terraform state but will remain in your Stripe account. "+
		"You may need to archive or deactivate it manually.",
		map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
