// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2BillingPricingPlan returns the schema for the stripe_v2_billing_pricing_plan resource
func ResourceV2BillingPricingPlan() *schema.Resource {
	return &schema.Resource{
		Description: "Manages a stripe_v2_billing_pricing_plan resource in Stripe.",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"currency": {
				Type:        schema.TypeString,
				Description: "The currency of the PricingPlan.",
				Required:    true,
				ForceNew:    true,
			},
			"description": {
				Type:        schema.TypeString,
				Description: "Description of pricing plan subscription.",
				Optional:    true,
				Computed:    true,
			},
			"display_name": {
				Type:        schema.TypeString,
				Description: "Display name of the PricingPlan. Maximum 250 characters.",
				Required:    true,
			},
			"lookup_key": {
				Type:        schema.TypeString,
				Description: "An internal key you can use to search for a particular PricingPlan. Maximum length of 200 characters.",
				Optional:    true,
				Computed:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				Optional:    true,
				Computed:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"tax_behavior": {
				Type:        schema.TypeString,
				Description: "The Stripe Tax tax behavior - whether the PricingPlan is inclusive or exclusive of tax.",
				Required:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"exclusive",
					"inclusive",
				}, false)),
			},
		},

		CreateContext: resourceV2BillingPricingPlanCreate,
		ReadContext:   resourceV2BillingPricingPlanRead,
		UpdateContext: resourceV2BillingPricingPlanUpdate,
		DeleteContext: resourceV2BillingPricingPlanDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2BillingPricingPlanCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_billing_pricing_plan resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingPricingPlanCreateParams{}

	if v, ok := d.Get("currency").(string); ok && v != "" {
		params.Currency = stripe.String(v)
	}
	if v, ok := d.Get("description").(string); ok && v != "" {
		params.Description = stripe.String(v)
	}
	if v, ok := d.Get("display_name").(string); ok && v != "" {
		params.DisplayName = stripe.String(v)
	}
	if v, ok := d.Get("lookup_key").(string); ok && v != "" {
		params.LookupKey = stripe.String(v)
	}
	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("tax_behavior").(string); ok && v != "" {
		params.TaxBehavior = stripe.String(v)
	}
	v2_billing_pricing_plan, err := c.V2BillingPricingPlans.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_billing_pricing_plan: %w", err))
	}

	d.SetId(v2_billing_pricing_plan.ID)
	return resourceV2BillingPricingPlanRead(ctx, d, meta)
}

func resourceV2BillingPricingPlanRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_billing_pricing_plan resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	v2_billing_pricing_plan, err := c.V2BillingPricingPlans.Retrieve(ctx, d.Id(), nil)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_billing_pricing_plan: %w", err))
	}

	if err := d.Set("currency", v2_billing_pricing_plan.Currency); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("description", v2_billing_pricing_plan.Description); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("display_name", v2_billing_pricing_plan.DisplayName); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("lookup_key", v2_billing_pricing_plan.LookupKey); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("metadata", v2_billing_pricing_plan.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tax_behavior", v2_billing_pricing_plan.TaxBehavior); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	return diags
}

func resourceV2BillingPricingPlanUpdate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Updating stripe_v2_billing_pricing_plan resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingPricingPlanUpdateParams{}

	if d.HasChange("description") {
		if v, ok := d.Get("description").(string); ok && v != "" {
			params.Description = stripe.String(v)
		}
	}
	if d.HasChange("display_name") {
		if v, ok := d.Get("display_name").(string); ok && v != "" {
			params.DisplayName = stripe.String(v)
		}
	}
	if d.HasChange("lookup_key") {
		if v, ok := d.Get("lookup_key").(string); ok && v != "" {
			params.LookupKey = stripe.String(v)
		}
	}
	if d.HasChange("metadata") {
		// Handle metadata updates including deletions (V2 uses *string)
		old, new := d.GetChange("metadata")
		oldMap := make(map[string]string)
		if old != nil {
			if oldMeta, ok := old.(map[string]interface{}); ok {
				for k, v := range oldMeta {
					oldMap[k] = v.(string)
				}
			}
		}
		params.Metadata = make(map[string]*string)
		// Add/update keys from new metadata
		if new != nil {
			if newMeta, ok := new.(map[string]interface{}); ok {
				for k, v := range newMeta {
					params.Metadata[k] = stripe.String(v.(string))
				}
			}
		}
		// Mark removed keys for deletion by setting to empty string
		for k := range oldMap {
			if _, exists := params.Metadata[k]; !exists {
				params.Metadata[k] = stripe.String("")
			}
		}
	}
	// Skip update if no fields were actually changed
	// This handles cases where fields are removed from config (HasChange returns true but new value is empty)
	if !paramsHasFields(params) {
		return resourceV2BillingPricingPlanRead(ctx, d, meta)
	}

	_, err := c.V2BillingPricingPlans.Update(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to update v2_billing_pricing_plan: %w", err))
	}

	return resourceV2BillingPricingPlanRead(ctx, d, meta)
}

func resourceV2BillingPricingPlanDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Warn(ctx, "stripe_v2_billing_pricing_plan resources cannot be deleted via the Stripe API. "+
		"The resource will be removed from Terraform state but will remain in your Stripe account. "+
		"You may need to archive or deactivate it manually.",
		map[string]interface{}{"id": d.Id()})
	d.SetId("")
	return nil
}
