// Code generated by stripe-terraform generator. DO NOT EDIT.

package resources

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-log/tflog"
	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
	"github.com/stripe/stripe-go/v84"
)

// ResourceV2BillingRateCardRate returns the schema for the stripe_v2_billing_rate_card_rate resource
func ResourceV2BillingRateCardRate() *schema.Resource {
	return &schema.Resource{
		Description: "Manages a stripe_v2_billing_rate_card_rate resource in Stripe.",

		Schema: map[string]*schema.Schema{
			"id": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"rate_card_id": {
				Type:        schema.TypeString,
				Description: "Path parameter: rate_card_id",
				Required:    true,
				ForceNew:    true,
			},
			"metadata": {
				Type:        schema.TypeMap,
				Description: "Set of [key-value pairs](/docs/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				Elem:        &schema.Schema{Type: schema.TypeString},
			},
			"metered_item": {
				Type:        schema.TypeString,
				Description: "The Metered Item that this rate binds to.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
			},
			"tiering_mode": {
				Type:        schema.TypeString,
				Description: "Defines whether the tiered price should be graduated or volume-based. In volume-based tiering, the maximum quantity within a period determines the per-unit price. In graduated tiering, the pricing changes as the quantity grows into new tiers. Can only be set if `tiers` is set.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
				ValidateDiagFunc: validation.ToDiagFunc(validation.StringInSlice([]string{
					"graduated",
					"volume",
				}, false)),
			},
			"unit_amount": {
				Type:        schema.TypeString,
				Description: "The per-unit amount to be charged, represented as a decimal string in minor currency units with at most 12 decimal places. Cannot be set if `tiers` is provided.",
				Optional:    true,
				Computed:    true,
				ForceNew:    true,
			},
			"tiers": {
				Type:        schema.TypeList,
				Optional:    true,
				ForceNew:    true,
				Description: "Each element represents a pricing tier. Cannot be set if `unit_amount` is provided.",
				Elem: &schema.Resource{
					Schema: map[string]*schema.Schema{
						"flat_amount": {
							Type:        schema.TypeString,
							Description: "Price for the entire tier, represented as a decimal string in minor currency units with at most 12 decimal places.",
							Optional:    true,
						},
						"unit_amount": {
							Type:        schema.TypeString,
							Description: "Per-unit price for units included in this tier, represented as a decimal string in minor currency units with at most 12 decimal places.",
							Optional:    true,
						},
						"up_to_decimal": {
							Type:        schema.TypeString,
							Description: "Up to and including this quantity will be contained in the tier. Only one of `up_to_decimal` and `up_to_inf` may be set.",
							Optional:    true,
						},
						"up_to_inf": {
							Type:        schema.TypeString,
							Description: "No upper bound to this tier. Only one of `up_to_decimal` and `up_to_inf` may be set.",
							Optional:    true,
						},
					},
				},
			},
		},

		CreateContext: resourceV2BillingRateCardRateCreate,
		ReadContext:   resourceV2BillingRateCardRateRead,
		DeleteContext: resourceV2BillingRateCardRateDelete,

		Importer: &schema.ResourceImporter{
			StateContext: schema.ImportStatePassthroughContext,
		},
	}
}

func resourceV2BillingRateCardRateCreate(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Creating stripe_v2_billing_rate_card_rate resource")
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingRateCardsRateCreateParams{}

	if v, ok := d.Get("rate_card_id").(string); ok && v != "" {
		params.RateCardID = stripe.String(v)
	}

	if v, ok := d.Get("metadata").(map[string]interface{}); ok && len(v) > 0 {
		params.Metadata = make(map[string]string)
		for k, val := range v {
			params.Metadata[k] = val.(string)
		}
	}
	if v, ok := d.Get("metered_item").(string); ok && v != "" {
		params.MeteredItem = stripe.String(v)
	}
	if v, ok := d.Get("tiering_mode").(string); ok && v != "" {
		params.TieringMode = stripe.String(v)
	}
	if v, ok := d.Get("unit_amount").(string); ok && v != "" {
		params.UnitAmount = stripe.String(v)
	}
	if v, ok := d.Get("tiers").([]interface{}); ok && len(v) > 0 {
		conditions := make([]*stripe.V2BillingRateCardsRateCreateTierParams, len(v))
		for i, item := range v {
			data := item.(map[string]interface{})
			condition := &stripe.V2BillingRateCardsRateCreateTierParams{}
			if flat_amount, ok := data["flat_amount"].(string); ok && flat_amount != "" {
				condition.FlatAmount = stripe.String(flat_amount)
			}
			if unit_amount, ok := data["unit_amount"].(string); ok && unit_amount != "" {
				condition.UnitAmount = stripe.String(unit_amount)
			}
			if up_to_decimal, ok := data["up_to_decimal"].(string); ok && up_to_decimal != "" {
				condition.UpToDecimal = stripe.String(up_to_decimal)
			}
			if up_to_inf, ok := data["up_to_inf"].(string); ok && up_to_inf != "" {
				condition.UpToInf = stripe.String(up_to_inf)
			}
			conditions[i] = condition
		}
		params.Tiers = conditions
	}
	v2_billing_rate_card_rate, err := c.V2BillingRateCardsRates.Create(ctx, params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to create v2_billing_rate_card_rate: %w", err))
	}

	d.SetId(v2_billing_rate_card_rate.ID)
	return resourceV2BillingRateCardRateRead(ctx, d, meta)
}

func resourceV2BillingRateCardRateRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	var diags diag.Diagnostics
	tflog.Debug(ctx, "Reading stripe_v2_billing_rate_card_rate resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingRateCardsRateRetrieveParams{}
	if v, ok := d.Get("rate_card_id").(string); ok && v != "" {
		params.RateCardID = stripe.String(v)
	}

	v2_billing_rate_card_rate, err := c.V2BillingRateCardsRates.Retrieve(ctx, d.Id(), params)
	if err != nil {
		// Check if it's a 404 (resource was deleted) vs other errors
		if stripeErr, ok := err.(*stripe.Error); ok && stripeErr.HTTPStatusCode == 404 {
			// Resource was deleted
			d.SetId("")
			return diags
		}
		// Other errors should be returned as diagnostics
		return diag.FromErr(fmt.Errorf("failed to read v2_billing_rate_card_rate: %w", err))
	}

	if err := d.Set("metadata", v2_billing_rate_card_rate.Metadata); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("tiering_mode", v2_billing_rate_card_rate.TieringMode); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if err := d.Set("unit_amount", normalizeDecimalString(v2_billing_rate_card_rate.UnitAmount)); err != nil {
		diags = append(diags, diag.FromErr(err)...)
	}
	if v2_billing_rate_card_rate.MeteredItem != nil {
		if err := d.Set("metered_item", v2_billing_rate_card_rate.MeteredItem.ID); err != nil {
			diags = append(diags, diag.FromErr(err)...)
		}
	}
	if _, ok := d.GetOk("tiers"); ok {
		if v2_billing_rate_card_rate.Tiers != nil && len(v2_billing_rate_card_rate.Tiers) > 0 {
			itemsData := make([]interface{}, len(v2_billing_rate_card_rate.Tiers))
			for i, item := range v2_billing_rate_card_rate.Tiers {
				itemData := make(map[string]interface{})
				if item.FlatAmount != "" {
					itemData["flat_amount"] = item.FlatAmount
				}
				if item.UnitAmount != "" {
					itemData["unit_amount"] = item.UnitAmount
				}
				if item.UpToDecimal != "" {
					itemData["up_to_decimal"] = item.UpToDecimal
				}
				if item.UpToInf != "" {
					itemData["up_to_inf"] = item.UpToInf
				}
				itemsData[i] = itemData
			}
			if err := d.Set("tiers", itemsData); err != nil {
				diags = append(diags, diag.FromErr(err)...)
			}
		}
	}
	return diags
}

func resourceV2BillingRateCardRateDelete(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	tflog.Debug(ctx, "Deleting stripe_v2_billing_rate_card_rate resource", map[string]interface{}{"id": d.Id()})
	c := meta.(*stripe.Client)

	params := &stripe.V2BillingRateCardsRateDeleteParams{}
	if v, ok := d.Get("rate_card_id").(string); ok && v != "" {
		params.RateCardID = stripe.String(v)
	}

	_, err := c.V2BillingRateCardsRates.Delete(ctx, d.Id(), params)
	if err != nil {
		return diag.FromErr(fmt.Errorf("failed to delete v2_billing_rate_card_rate: %w", err))
	}

	d.SetId("")
	return nil
}
