// Code generated by stripe-terraform generator. DO NOT EDIT.

package datasources

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/stripe/stripe-go/v84"
)

// DataSourceBillingMeter returns the data source for reading Stripe stripe_billing_meter
func DataSourceBillingMeter() *schema.Resource {
	return &schema.Resource{
		Description: "Use this data source to retrieve information about an existing Stripe Billing Meter.",
		ReadContext: dataSourceBillingMeterRead,

		Schema: map[string]*schema.Schema{
			"id": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Unique identifier for the object",
			},
			"event_name": {
				Type:        schema.TypeString,
				Optional:    true,
				Computed:    true,
				Description: "Event name for the meter",
			},
			"display_name": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Display name of the meter",
			},
			"status": {
				Type:        schema.TypeString,
				Computed:    true,
				Description: "Status of the meter",
			},
		},
	}
}

func dataSourceBillingMeterRead(ctx context.Context, d *schema.ResourceData, meta interface{}) diag.Diagnostics {
	client := meta.(*stripe.Client)

	// If ID is provided, fetch directly
	if id, ok := d.GetOk("id"); ok {
		obj, err := client.V1BillingMeters.Retrieve(ctx, id.(string), nil)
		if err != nil {
			return diag.FromErr(err)
		}
		return dataSourceBillingMeterSetData(d, obj)
	}

	// Filter by event_name if provided (client-side filtering)
	if eventName, ok := d.GetOk("event_name"); ok {
		params := &stripe.BillingMeterListParams{}
		params.Status = stripe.String("active")

		for obj, err := range client.V1BillingMeters.List(ctx, params) {
			if err != nil {
				return diag.FromErr(err)
			}
			// Client-side filter by event_name
			if obj.EventName == eventName.(string) {
				return dataSourceBillingMeterSetData(d, obj)
			}
		}

		return diag.Errorf("no active billing meter found with event_name: %s", eventName.(string))
	}

	return diag.Errorf("must provide either id or event_name")
}

func dataSourceBillingMeterSetData(d *schema.ResourceData, obj *stripe.BillingMeter) diag.Diagnostics {
	d.SetId(obj.ID)
	d.Set("event_name", obj.EventName)
	d.Set("display_name", obj.DisplayName)
	d.Set("status", obj.Status)
	return nil
}
