//
// File generated from our OpenAPI spec
//

package actions

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/action"
	actionSchema "github.com/hashicorp/terraform-plugin-framework/action/schema"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	stripe "github.com/stripe/stripe-go/v86"
)

var _ action.Action = &RefundAction{}
var _ action.ActionWithConfigure = &RefundAction{}

func NewRefundAction() action.Action {
	return &RefundAction{}
}

type RefundAction struct {
	client *stripe.Client
}

type RefundResourceModel struct {
	Amount               types.Int64  `tfsdk:"amount"`
	Charge               types.String `tfsdk:"charge"`
	Currency             types.String `tfsdk:"currency"`
	InstructionsEmail    types.String `tfsdk:"instructions_email"`
	Metadata             types.Map    `tfsdk:"metadata"`
	PaymentIntent        types.String `tfsdk:"payment_intent"`
	Reason               types.String `tfsdk:"reason"`
	Customer             types.String `tfsdk:"customer"`
	Origin               types.String `tfsdk:"origin"`
	RefundApplicationFee types.Bool   `tfsdk:"refund_application_fee"`
	ReverseTransfer      types.Bool   `tfsdk:"reverse_transfer"`
}

func (r *RefundAction) Metadata(_ context.Context, req action.MetadataRequest, resp *action.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_refund"
}

func (r *RefundAction) Schema(_ context.Context, _ action.SchemaRequest, resp *action.SchemaResponse) {
	resp.Schema = actionSchema.Schema{
		Description: "Refund objects allow you to refund a previously created charge that isn't\nrefunded yet. Funds are refunded to the credit or debit card that's\ninitially charged.\n\nRelated guide: [Refunds](https://docs.stripe.com/refunds)",
		Attributes: map[string]actionSchema.Attribute{
			"amount": actionSchema.Int64Attribute{
				Optional:    true,
				Description: "Amount, in cents (or local equivalent).",
			},
			"charge": actionSchema.StringAttribute{
				Optional:    true,
				Description: "ID of the charge that's refunded.",
			},
			"currency": actionSchema.StringAttribute{
				Optional:    true,
				Description: "Three-letter [ISO currency code](https://www.iso.org/iso-4217-currency-codes.html), in lowercase. Must be a [supported currency](https://stripe.com/docs/currencies).",
			},
			"instructions_email": actionSchema.StringAttribute{
				Optional:    true,
				Description: "For payment methods without native refund support (for example, Konbini, PromptPay), provide an email address for the customer to receive refund instructions.",
			},
			"metadata": actionSchema.MapAttribute{
				Optional:    true,
				Description: "Set of [key-value pairs](https://docs.stripe.com/api/metadata) that you can attach to an object. This can be useful for storing additional information about the object in a structured format.",
				ElementType: types.StringType,
			},
			"payment_intent": actionSchema.StringAttribute{
				Optional:    true,
				Description: "ID of the PaymentIntent that's refunded.",
			},
			"reason": actionSchema.StringAttribute{
				Optional:    true,
				Description: "Reason for the refund, which is either user-provided (`duplicate`, `fraudulent`, or `requested_by_customer`) or generated by Stripe internally (`expired_uncaptured_charge`).",
				Validators:  []validator.String{stringvalidator.OneOf("duplicate", "expired_uncaptured_charge", "fraudulent", "requested_by_customer")},
			},
			"customer": actionSchema.StringAttribute{
				Optional:    true,
				Description: "Customer whose customer balance to refund from.",
			},
			"origin": actionSchema.StringAttribute{
				Optional:    true,
				Description: "Origin of the refund",
				Validators:  []validator.String{stringvalidator.OneOf("customer_balance")},
			},
			"refund_application_fee": actionSchema.BoolAttribute{
				Optional:    true,
				Description: "Boolean indicating whether the application fee should be refunded when refunding this charge. If a full charge refund is given, the full application fee will be refunded. Otherwise, the application fee will be refunded in an amount proportional to the amount of the charge refunded. An application fee can be refunded only by the application that created the charge.",
			},
			"reverse_transfer": actionSchema.BoolAttribute{
				Optional:    true,
				Description: "Boolean indicating whether the transfer should be reversed when refunding this charge. The transfer will be reversed proportionally to the amount being refunded (either the entire or partial amount).<br><br>A transfer can be reversed only by the application that created the charge.",
			},
		},
	}
}

func (r *RefundAction) Configure(_ context.Context, req action.ConfigureRequest, resp *action.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}

	client, ok := req.ProviderData.(*stripe.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Action Configure Type", fmt.Sprintf("Expected *stripe.Client, got: %T", req.ProviderData))
		return
	}

	r.client = client
}

func expandRefundCreate(plan RefundResourceModel) (*stripe.RefundCreateParams, error) {
	params := &stripe.RefundCreateParams{}

	if !plan.Amount.IsNull() && !plan.Amount.IsUnknown() {
		params.Amount = stripe.Int64(plan.Amount.ValueInt64())
	}
	if !plan.Charge.IsNull() && !plan.Charge.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "ChargeID", "Charge", plan.Charge.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "charge", params)
		}
	}
	if !plan.Currency.IsNull() && !plan.Currency.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "Currency", "Currency", plan.Currency.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "currency", params)
		}
	}
	if !plan.InstructionsEmail.IsNull() && !plan.InstructionsEmail.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "InstructionsEmail", "InstructionsEmail", plan.InstructionsEmail.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "instructions_email", params)
		}
	}
	if !plan.Metadata.IsNull() && !plan.Metadata.IsUnknown() {
		if !assignAttrValueToNamedField(params, "Metadata", plan.Metadata) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "metadata", params)
		}
	}
	if !plan.PaymentIntent.IsNull() && !plan.PaymentIntent.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "PaymentIntentID", "PaymentIntent", plan.PaymentIntent.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "payment_intent", params)
		}
	}
	if !plan.Reason.IsNull() && !plan.Reason.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "Reason", "Reason", plan.Reason.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "reason", params)
		}
	}
	if !plan.Customer.IsNull() && !plan.Customer.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "Customer", "Customer", plan.Customer.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "customer", params)
		}
	}
	if !plan.Origin.IsNull() && !plan.Origin.IsUnknown() {
		if !assignStringToNamedFieldOrMethod(params, "Origin", "Origin", plan.Origin.ValueString()) {
			return nil, fmt.Errorf("failed to assign attribute %q on %T", "origin", params)
		}
	}
	if !plan.RefundApplicationFee.IsNull() && !plan.RefundApplicationFee.IsUnknown() {
		params.RefundApplicationFee = stripe.Bool(plan.RefundApplicationFee.ValueBool())
	}
	if !plan.ReverseTransfer.IsNull() && !plan.ReverseTransfer.IsUnknown() {
		params.ReverseTransfer = stripe.Bool(plan.ReverseTransfer.ValueBool())
	}

	return params, nil
}

func (r *RefundAction) Invoke(ctx context.Context, req action.InvokeRequest, resp *action.InvokeResponse) {
	var config RefundResourceModel
	diags := req.Config.Get(ctx, &config)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	params, err := expandRefundCreate(config)
	if err != nil {
		resp.Diagnostics.AddError("Error building Refund action params", err.Error())
		return
	}

	obj, err := r.client.V1Refunds.Create(ctx, params)
	if err != nil {
		resp.Diagnostics.AddError("Error invoking Refund action", err.Error())
		return
	}

	if resp.SendProgress != nil {
		resp.SendProgress(action.InvokeProgressEvent{Message: fmt.Sprintf("Created stripe_refund %s", obj.ID)})
	}
}
