// Code generated by stripe-terraform generator. DO NOT EDIT.

package provider

import (
	"context"

	"github.com/hashicorp/terraform-plugin-sdk/v2/diag"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/stripe/stripe-go/v84"

	"github.com/stripe/stripe-terraform/internal/provider/datasources"
	"github.com/stripe/stripe-terraform/internal/provider/resources"
)

// New returns a new Stripe Terraform provider
func New(version string) func() *schema.Provider {
	return func() *schema.Provider {
		p := &schema.Provider{
			Schema: map[string]*schema.Schema{
				"api_key": {
					Type:        schema.TypeString,
					Required:    true,
					Sensitive:   true,
					Description: "Stripe API key",
					DefaultFunc: schema.EnvDefaultFunc("STRIPE_API_KEY", nil),
				},
			},

			ResourcesMap: map[string]*schema.Resource{
				"stripe_product":                           resources.ResourceProduct(),
				"stripe_price":                             resources.ResourcePrice(),
				"stripe_customer":                          resources.ResourceCustomer(),
				"stripe_coupon":                            resources.ResourceCoupon(),
				"stripe_promotion_code":                    resources.ResourcePromotionCode(),
				"stripe_shipping_rate":                     resources.ResourceShippingRate(),
				"stripe_tax_rate":                          resources.ResourceTaxRate(),
				"stripe_entitlements_feature":              resources.ResourceEntitlementsFeature(),
				"stripe_webhook_endpoint":                  resources.ResourceWebhookEndpoint(),
				"stripe_billing_meter":                     resources.ResourceBillingMeter(),
				"stripe_v2_billing_pricing_plan":           resources.ResourceV2BillingPricingPlan(),
				"stripe_v2_billing_pricing_plan_component": resources.ResourceV2BillingPricingPlanComponent(),
				"stripe_v2_billing_licensed_item":          resources.ResourceV2BillingLicensedItem(),
				"stripe_v2_billing_license_fee":            resources.ResourceV2BillingLicenseFee(),
				"stripe_v2_billing_metered_item":           resources.ResourceV2BillingMeteredItem(),
				"stripe_v2_billing_rate_card":              resources.ResourceV2BillingRateCard(),
				"stripe_v2_billing_rate_card_rate":         resources.ResourceV2BillingRateCardRate(),
				"stripe_v2_billing_service_action":         resources.ResourceV2BillingServiceAction(),
			},

			DataSourcesMap: map[string]*schema.Resource{
				"stripe_billing_meter": datasources.DataSourceBillingMeter(),
			},
		}

		p.ConfigureContextFunc = configure(version, p)

		return p
	}
}

func configure(version string, p *schema.Provider) func(context.Context, *schema.ResourceData) (interface{}, diag.Diagnostics) {
	return func(ctx context.Context, d *schema.ResourceData) (interface{}, diag.Diagnostics) {
		var diags diag.Diagnostics

		apiKey := d.Get("api_key").(string)

		// Set app info to identify requests from this Terraform provider
		stripe.SetAppInfo(&stripe.AppInfo{
			Name:    "stripe-terraform",
			Version: version,
		})

		// Create Stripe client with API key
		client := stripe.NewClient(apiKey)

		return client, diags
	}
}
